// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message_wrapper.proto
// Protobuf Java Version: 4.31.1

package com.fxy.game.message;

/**
 * Protobuf type {@code game.GameState}
 */
@com.google.protobuf.Generated
public final class GameState extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:game.GameState)
    GameStateOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      GameState.class.getName());
  }
  // Use GameState.newBuilder() to construct.
  private GameState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GameState() {
    players_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fxy.game.message.GameMessage.internal_static_game_GameState_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fxy.game.message.GameMessage.internal_static_game_GameState_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fxy.game.message.GameState.class, com.fxy.game.message.GameState.Builder.class);
  }

  private int bitField0_;
  public static final int PLAYERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.fxy.game.message.Player> players_;
  /**
   * <code>repeated .game.Player players = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.fxy.game.message.Player> getPlayersList() {
    return players_;
  }
  /**
   * <code>repeated .game.Player players = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.fxy.game.message.PlayerOrBuilder> 
      getPlayersOrBuilderList() {
    return players_;
  }
  /**
   * <code>repeated .game.Player players = 1;</code>
   */
  @java.lang.Override
  public int getPlayersCount() {
    return players_.size();
  }
  /**
   * <code>repeated .game.Player players = 1;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.Player getPlayers(int index) {
    return players_.get(index);
  }
  /**
   * <code>repeated .game.Player players = 1;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.PlayerOrBuilder getPlayersOrBuilder(
      int index) {
    return players_.get(index);
  }

  public static final int SERVERTIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp serverTime_;
  /**
   * <code>.google.protobuf.Timestamp serverTime = 2;</code>
   * @return Whether the serverTime field is set.
   */
  @java.lang.Override
  public boolean hasServerTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp serverTime = 2;</code>
   * @return The serverTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getServerTime() {
    return serverTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : serverTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp serverTime = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getServerTimeOrBuilder() {
    return serverTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : serverTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < players_.size(); i++) {
      output.writeMessage(1, players_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getServerTime());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < players_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, players_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getServerTime());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fxy.game.message.GameState)) {
      return super.equals(obj);
    }
    com.fxy.game.message.GameState other = (com.fxy.game.message.GameState) obj;

    if (!getPlayersList()
        .equals(other.getPlayersList())) return false;
    if (hasServerTime() != other.hasServerTime()) return false;
    if (hasServerTime()) {
      if (!getServerTime()
          .equals(other.getServerTime())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPlayersCount() > 0) {
      hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getPlayersList().hashCode();
    }
    if (hasServerTime()) {
      hash = (37 * hash) + SERVERTIME_FIELD_NUMBER;
      hash = (53 * hash) + getServerTime().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fxy.game.message.GameState parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fxy.game.message.GameState parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fxy.game.message.GameState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fxy.game.message.GameState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fxy.game.message.GameState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fxy.game.message.GameState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fxy.game.message.GameState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.fxy.game.message.GameState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.fxy.game.message.GameState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.fxy.game.message.GameState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fxy.game.message.GameState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.fxy.game.message.GameState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fxy.game.message.GameState prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code game.GameState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:game.GameState)
      com.fxy.game.message.GameStateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fxy.game.message.GameMessage.internal_static_game_GameState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fxy.game.message.GameMessage.internal_static_game_GameState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fxy.game.message.GameState.class, com.fxy.game.message.GameState.Builder.class);
    }

    // Construct using com.fxy.game.message.GameState.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetPlayersFieldBuilder();
        internalGetServerTimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
      } else {
        players_ = null;
        playersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      serverTime_ = null;
      if (serverTimeBuilder_ != null) {
        serverTimeBuilder_.dispose();
        serverTimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fxy.game.message.GameMessage.internal_static_game_GameState_descriptor;
    }

    @java.lang.Override
    public com.fxy.game.message.GameState getDefaultInstanceForType() {
      return com.fxy.game.message.GameState.getDefaultInstance();
    }

    @java.lang.Override
    public com.fxy.game.message.GameState build() {
      com.fxy.game.message.GameState result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.fxy.game.message.GameState buildPartial() {
      com.fxy.game.message.GameState result = new com.fxy.game.message.GameState(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.fxy.game.message.GameState result) {
      if (playersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          players_ = java.util.Collections.unmodifiableList(players_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.players_ = players_;
      } else {
        result.players_ = playersBuilder_.build();
      }
    }

    private void buildPartial0(com.fxy.game.message.GameState result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.serverTime_ = serverTimeBuilder_ == null
            ? serverTime_
            : serverTimeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fxy.game.message.GameState) {
        return mergeFrom((com.fxy.game.message.GameState)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fxy.game.message.GameState other) {
      if (other == com.fxy.game.message.GameState.getDefaultInstance()) return this;
      if (playersBuilder_ == null) {
        if (!other.players_.isEmpty()) {
          if (players_.isEmpty()) {
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePlayersIsMutable();
            players_.addAll(other.players_);
          }
          onChanged();
        }
      } else {
        if (!other.players_.isEmpty()) {
          if (playersBuilder_.isEmpty()) {
            playersBuilder_.dispose();
            playersBuilder_ = null;
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000001);
            playersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetPlayersFieldBuilder() : null;
          } else {
            playersBuilder_.addAllMessages(other.players_);
          }
        }
      }
      if (other.hasServerTime()) {
        mergeServerTime(other.getServerTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.fxy.game.message.Player m =
                  input.readMessage(
                      com.fxy.game.message.Player.parser(),
                      extensionRegistry);
              if (playersBuilder_ == null) {
                ensurePlayersIsMutable();
                players_.add(m);
              } else {
                playersBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetServerTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.fxy.game.message.Player> players_ =
      java.util.Collections.emptyList();
    private void ensurePlayersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        players_ = new java.util.ArrayList<com.fxy.game.message.Player>(players_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.fxy.game.message.Player, com.fxy.game.message.Player.Builder, com.fxy.game.message.PlayerOrBuilder> playersBuilder_;

    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public java.util.List<com.fxy.game.message.Player> getPlayersList() {
      if (playersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(players_);
      } else {
        return playersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public int getPlayersCount() {
      if (playersBuilder_ == null) {
        return players_.size();
      } else {
        return playersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public com.fxy.game.message.Player getPlayers(int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);
      } else {
        return playersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public Builder setPlayers(
        int index, com.fxy.game.message.Player value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.set(index, value);
        onChanged();
      } else {
        playersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public Builder setPlayers(
        int index, com.fxy.game.message.Player.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.set(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public Builder addPlayers(com.fxy.game.message.Player value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(value);
        onChanged();
      } else {
        playersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public Builder addPlayers(
        int index, com.fxy.game.message.Player value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(index, value);
        onChanged();
      } else {
        playersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public Builder addPlayers(
        com.fxy.game.message.Player.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public Builder addPlayers(
        int index, com.fxy.game.message.Player.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public Builder addAllPlayers(
        java.lang.Iterable<? extends com.fxy.game.message.Player> values) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, players_);
        onChanged();
      } else {
        playersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public Builder clearPlayers() {
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        playersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public Builder removePlayers(int index) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.remove(index);
        onChanged();
      } else {
        playersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public com.fxy.game.message.Player.Builder getPlayersBuilder(
        int index) {
      return internalGetPlayersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public com.fxy.game.message.PlayerOrBuilder getPlayersOrBuilder(
        int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);  } else {
        return playersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public java.util.List<? extends com.fxy.game.message.PlayerOrBuilder> 
         getPlayersOrBuilderList() {
      if (playersBuilder_ != null) {
        return playersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(players_);
      }
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public com.fxy.game.message.Player.Builder addPlayersBuilder() {
      return internalGetPlayersFieldBuilder().addBuilder(
          com.fxy.game.message.Player.getDefaultInstance());
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public com.fxy.game.message.Player.Builder addPlayersBuilder(
        int index) {
      return internalGetPlayersFieldBuilder().addBuilder(
          index, com.fxy.game.message.Player.getDefaultInstance());
    }
    /**
     * <code>repeated .game.Player players = 1;</code>
     */
    public java.util.List<com.fxy.game.message.Player.Builder> 
         getPlayersBuilderList() {
      return internalGetPlayersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.fxy.game.message.Player, com.fxy.game.message.Player.Builder, com.fxy.game.message.PlayerOrBuilder> 
        internalGetPlayersFieldBuilder() {
      if (playersBuilder_ == null) {
        playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.fxy.game.message.Player, com.fxy.game.message.Player.Builder, com.fxy.game.message.PlayerOrBuilder>(
                players_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        players_ = null;
      }
      return playersBuilder_;
    }

    private com.google.protobuf.Timestamp serverTime_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> serverTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp serverTime = 2;</code>
     * @return Whether the serverTime field is set.
     */
    public boolean hasServerTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp serverTime = 2;</code>
     * @return The serverTime.
     */
    public com.google.protobuf.Timestamp getServerTime() {
      if (serverTimeBuilder_ == null) {
        return serverTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : serverTime_;
      } else {
        return serverTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp serverTime = 2;</code>
     */
    public Builder setServerTime(com.google.protobuf.Timestamp value) {
      if (serverTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        serverTime_ = value;
      } else {
        serverTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp serverTime = 2;</code>
     */
    public Builder setServerTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (serverTimeBuilder_ == null) {
        serverTime_ = builderForValue.build();
      } else {
        serverTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp serverTime = 2;</code>
     */
    public Builder mergeServerTime(com.google.protobuf.Timestamp value) {
      if (serverTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          serverTime_ != null &&
          serverTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getServerTimeBuilder().mergeFrom(value);
        } else {
          serverTime_ = value;
        }
      } else {
        serverTimeBuilder_.mergeFrom(value);
      }
      if (serverTime_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp serverTime = 2;</code>
     */
    public Builder clearServerTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      serverTime_ = null;
      if (serverTimeBuilder_ != null) {
        serverTimeBuilder_.dispose();
        serverTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp serverTime = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getServerTimeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetServerTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp serverTime = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getServerTimeOrBuilder() {
      if (serverTimeBuilder_ != null) {
        return serverTimeBuilder_.getMessageOrBuilder();
      } else {
        return serverTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : serverTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp serverTime = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetServerTimeFieldBuilder() {
      if (serverTimeBuilder_ == null) {
        serverTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getServerTime(),
                getParentForChildren(),
                isClean());
        serverTime_ = null;
      }
      return serverTimeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:game.GameState)
  }

  // @@protoc_insertion_point(class_scope:game.GameState)
  private static final com.fxy.game.message.GameState DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fxy.game.message.GameState();
  }

  public static com.fxy.game.message.GameState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GameState>
      PARSER = new com.google.protobuf.AbstractParser<GameState>() {
    @java.lang.Override
    public GameState parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GameState> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameState> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.fxy.game.message.GameState getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

