// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message_wrapper.proto
// Protobuf Java Version: 4.31.1

package com.fxy.game.message;

@com.google.protobuf.Generated
public interface GameStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.GameState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .game.Player players = 1;</code>
   */
  java.util.List<com.fxy.game.message.Player> 
      getPlayersList();
  /**
   * <code>repeated .game.Player players = 1;</code>
   */
  com.fxy.game.message.Player getPlayers(int index);
  /**
   * <code>repeated .game.Player players = 1;</code>
   */
  int getPlayersCount();
  /**
   * <code>repeated .game.Player players = 1;</code>
   */
  java.util.List<? extends com.fxy.game.message.PlayerOrBuilder> 
      getPlayersOrBuilderList();
  /**
   * <code>repeated .game.Player players = 1;</code>
   */
  com.fxy.game.message.PlayerOrBuilder getPlayersOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Timestamp serverTime = 2;</code>
   * @return Whether the serverTime field is set.
   */
  boolean hasServerTime();
  /**
   * <code>.google.protobuf.Timestamp serverTime = 2;</code>
   * @return The serverTime.
   */
  com.google.protobuf.Timestamp getServerTime();
  /**
   * <code>.google.protobuf.Timestamp serverTime = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getServerTimeOrBuilder();
}
