// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message_wrapper.proto
// Protobuf Java Version: 4.31.1

package com.fxy.game.message;

@com.google.protobuf.Generated
public interface GameActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.GameAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sessionId = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string sessionId = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>.game.GameAction.ActionType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.game.GameAction.ActionType type = 2;</code>
   * @return The type.
   */
  com.fxy.game.message.GameAction.ActionType getType();

  /**
   * <code>int32 x = 3;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>int32 y = 4;</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>int32 destX = 5;</code>
   * @return The destX.
   */
  int getDestX();

  /**
   * <code>int32 destY = 6;</code>
   * @return The destY.
   */
  int getDestY();
}
