// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message_wrapper.proto
// Protobuf Java Version: 4.31.1

package com.fxy.game.message;

/**
 * Protobuf type {@code game.MailResponse}
 */
@com.google.protobuf.Generated
public final class MailResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:game.MailResponse)
    MailResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      MailResponse.class.getName());
  }
  // Use MailResponse.newBuilder() to construct.
  private MailResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MailResponse() {
    mails_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fxy.game.message.GameMessage.internal_static_game_MailResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fxy.game.message.GameMessage.internal_static_game_MailResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fxy.game.message.MailResponse.class, com.fxy.game.message.MailResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_ = false;
  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int MAILS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.fxy.game.message.Mail> mails_;
  /**
   * <code>repeated .game.Mail mails = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.fxy.game.message.Mail> getMailsList() {
    return mails_;
  }
  /**
   * <code>repeated .game.Mail mails = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.fxy.game.message.MailOrBuilder> 
      getMailsOrBuilderList() {
    return mails_;
  }
  /**
   * <code>repeated .game.Mail mails = 2;</code>
   */
  @java.lang.Override
  public int getMailsCount() {
    return mails_.size();
  }
  /**
   * <code>repeated .game.Mail mails = 2;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.Mail getMails(int index) {
    return mails_.get(index);
  }
  /**
   * <code>repeated .game.Mail mails = 2;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.MailOrBuilder getMailsOrBuilder(
      int index) {
    return mails_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    for (int i = 0; i < mails_.size(); i++) {
      output.writeMessage(2, mails_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    for (int i = 0; i < mails_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, mails_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fxy.game.message.MailResponse)) {
      return super.equals(obj);
    }
    com.fxy.game.message.MailResponse other = (com.fxy.game.message.MailResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getMailsList()
        .equals(other.getMailsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    if (getMailsCount() > 0) {
      hash = (37 * hash) + MAILS_FIELD_NUMBER;
      hash = (53 * hash) + getMailsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fxy.game.message.MailResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fxy.game.message.MailResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fxy.game.message.MailResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fxy.game.message.MailResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fxy.game.message.MailResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fxy.game.message.MailResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fxy.game.message.MailResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.fxy.game.message.MailResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.fxy.game.message.MailResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.fxy.game.message.MailResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fxy.game.message.MailResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.fxy.game.message.MailResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fxy.game.message.MailResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code game.MailResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:game.MailResponse)
      com.fxy.game.message.MailResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fxy.game.message.GameMessage.internal_static_game_MailResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fxy.game.message.GameMessage.internal_static_game_MailResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fxy.game.message.MailResponse.class, com.fxy.game.message.MailResponse.Builder.class);
    }

    // Construct using com.fxy.game.message.MailResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      success_ = false;
      if (mailsBuilder_ == null) {
        mails_ = java.util.Collections.emptyList();
      } else {
        mails_ = null;
        mailsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fxy.game.message.GameMessage.internal_static_game_MailResponse_descriptor;
    }

    @java.lang.Override
    public com.fxy.game.message.MailResponse getDefaultInstanceForType() {
      return com.fxy.game.message.MailResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.fxy.game.message.MailResponse build() {
      com.fxy.game.message.MailResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.fxy.game.message.MailResponse buildPartial() {
      com.fxy.game.message.MailResponse result = new com.fxy.game.message.MailResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.fxy.game.message.MailResponse result) {
      if (mailsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          mails_ = java.util.Collections.unmodifiableList(mails_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.mails_ = mails_;
      } else {
        result.mails_ = mailsBuilder_.build();
      }
    }

    private void buildPartial0(com.fxy.game.message.MailResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.success_ = success_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fxy.game.message.MailResponse) {
        return mergeFrom((com.fxy.game.message.MailResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fxy.game.message.MailResponse other) {
      if (other == com.fxy.game.message.MailResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (mailsBuilder_ == null) {
        if (!other.mails_.isEmpty()) {
          if (mails_.isEmpty()) {
            mails_ = other.mails_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMailsIsMutable();
            mails_.addAll(other.mails_);
          }
          onChanged();
        }
      } else {
        if (!other.mails_.isEmpty()) {
          if (mailsBuilder_.isEmpty()) {
            mailsBuilder_.dispose();
            mailsBuilder_ = null;
            mails_ = other.mails_;
            bitField0_ = (bitField0_ & ~0x00000002);
            mailsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetMailsFieldBuilder() : null;
          } else {
            mailsBuilder_.addAllMessages(other.mails_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              success_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              com.fxy.game.message.Mail m =
                  input.readMessage(
                      com.fxy.game.message.Mail.parser(),
                      extensionRegistry);
              if (mailsBuilder_ == null) {
                ensureMailsIsMutable();
                mails_.add(m);
              } else {
                mailsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      success_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.fxy.game.message.Mail> mails_ =
      java.util.Collections.emptyList();
    private void ensureMailsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        mails_ = new java.util.ArrayList<com.fxy.game.message.Mail>(mails_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.fxy.game.message.Mail, com.fxy.game.message.Mail.Builder, com.fxy.game.message.MailOrBuilder> mailsBuilder_;

    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public java.util.List<com.fxy.game.message.Mail> getMailsList() {
      if (mailsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(mails_);
      } else {
        return mailsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public int getMailsCount() {
      if (mailsBuilder_ == null) {
        return mails_.size();
      } else {
        return mailsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public com.fxy.game.message.Mail getMails(int index) {
      if (mailsBuilder_ == null) {
        return mails_.get(index);
      } else {
        return mailsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public Builder setMails(
        int index, com.fxy.game.message.Mail value) {
      if (mailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMailsIsMutable();
        mails_.set(index, value);
        onChanged();
      } else {
        mailsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public Builder setMails(
        int index, com.fxy.game.message.Mail.Builder builderForValue) {
      if (mailsBuilder_ == null) {
        ensureMailsIsMutable();
        mails_.set(index, builderForValue.build());
        onChanged();
      } else {
        mailsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public Builder addMails(com.fxy.game.message.Mail value) {
      if (mailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMailsIsMutable();
        mails_.add(value);
        onChanged();
      } else {
        mailsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public Builder addMails(
        int index, com.fxy.game.message.Mail value) {
      if (mailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMailsIsMutable();
        mails_.add(index, value);
        onChanged();
      } else {
        mailsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public Builder addMails(
        com.fxy.game.message.Mail.Builder builderForValue) {
      if (mailsBuilder_ == null) {
        ensureMailsIsMutable();
        mails_.add(builderForValue.build());
        onChanged();
      } else {
        mailsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public Builder addMails(
        int index, com.fxy.game.message.Mail.Builder builderForValue) {
      if (mailsBuilder_ == null) {
        ensureMailsIsMutable();
        mails_.add(index, builderForValue.build());
        onChanged();
      } else {
        mailsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public Builder addAllMails(
        java.lang.Iterable<? extends com.fxy.game.message.Mail> values) {
      if (mailsBuilder_ == null) {
        ensureMailsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mails_);
        onChanged();
      } else {
        mailsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public Builder clearMails() {
      if (mailsBuilder_ == null) {
        mails_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        mailsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public Builder removeMails(int index) {
      if (mailsBuilder_ == null) {
        ensureMailsIsMutable();
        mails_.remove(index);
        onChanged();
      } else {
        mailsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public com.fxy.game.message.Mail.Builder getMailsBuilder(
        int index) {
      return internalGetMailsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public com.fxy.game.message.MailOrBuilder getMailsOrBuilder(
        int index) {
      if (mailsBuilder_ == null) {
        return mails_.get(index);  } else {
        return mailsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public java.util.List<? extends com.fxy.game.message.MailOrBuilder> 
         getMailsOrBuilderList() {
      if (mailsBuilder_ != null) {
        return mailsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(mails_);
      }
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public com.fxy.game.message.Mail.Builder addMailsBuilder() {
      return internalGetMailsFieldBuilder().addBuilder(
          com.fxy.game.message.Mail.getDefaultInstance());
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public com.fxy.game.message.Mail.Builder addMailsBuilder(
        int index) {
      return internalGetMailsFieldBuilder().addBuilder(
          index, com.fxy.game.message.Mail.getDefaultInstance());
    }
    /**
     * <code>repeated .game.Mail mails = 2;</code>
     */
    public java.util.List<com.fxy.game.message.Mail.Builder> 
         getMailsBuilderList() {
      return internalGetMailsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.fxy.game.message.Mail, com.fxy.game.message.Mail.Builder, com.fxy.game.message.MailOrBuilder> 
        internalGetMailsFieldBuilder() {
      if (mailsBuilder_ == null) {
        mailsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.fxy.game.message.Mail, com.fxy.game.message.Mail.Builder, com.fxy.game.message.MailOrBuilder>(
                mails_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        mails_ = null;
      }
      return mailsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:game.MailResponse)
  }

  // @@protoc_insertion_point(class_scope:game.MailResponse)
  private static final com.fxy.game.message.MailResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fxy.game.message.MailResponse();
  }

  public static com.fxy.game.message.MailResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MailResponse>
      PARSER = new com.google.protobuf.AbstractParser<MailResponse>() {
    @java.lang.Override
    public MailResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MailResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MailResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.fxy.game.message.MailResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

