// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message_wrapper.proto
// Protobuf Java Version: 4.31.1

package com.fxy.game.message;

@com.google.protobuf.Generated
public interface MailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.Mail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string from = 2;</code>
   * @return The from.
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 2;</code>
   * @return The bytes for from.
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string subject = 3;</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 3;</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>string body = 4;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 4;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <code>bool read = 5;</code>
   * @return The read.
   */
  boolean getRead();

  /**
   * <code>.google.protobuf.Timestamp sentTime = 6;</code>
   * @return Whether the sentTime field is set.
   */
  boolean hasSentTime();
  /**
   * <code>.google.protobuf.Timestamp sentTime = 6;</code>
   * @return The sentTime.
   */
  com.google.protobuf.Timestamp getSentTime();
  /**
   * <code>.google.protobuf.Timestamp sentTime = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getSentTimeOrBuilder();
}
