// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message_wrapper.proto
// Protobuf Java Version: 4.31.1

package com.fxy.game.message;

@com.google.protobuf.Generated
public interface PlayerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.Player)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sessionId = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string sessionId = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>int32 x = 3;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>int32 y = 4;</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>int32 hp = 5;</code>
   * @return The hp.
   */
  int getHp();

  /**
   * <code>int32 atk = 6;</code>
   * @return The atk.
   */
  int getAtk();

  /**
   * <code>int32 dfs = 7;</code>
   * @return The dfs.
   */
  int getDfs();

  /**
   * <code>.game.Role role = 8;</code>
   * @return Whether the role field is set.
   */
  boolean hasRole();
  /**
   * <code>.game.Role role = 8;</code>
   * @return The role.
   */
  com.fxy.game.message.Role getRole();
  /**
   * <code>.game.Role role = 8;</code>
   */
  com.fxy.game.message.RoleOrBuilder getRoleOrBuilder();
}
