// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message_wrapper.proto
// Protobuf Java Version: 4.31.1

package com.fxy.game.message;

/**
 * Protobuf type {@code game.Player}
 */
@com.google.protobuf.Generated
public final class Player extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:game.Player)
    PlayerOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Player.class.getName());
  }
  // Use Player.newBuilder() to construct.
  private Player(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Player() {
    sessionId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fxy.game.message.GameMessage.internal_static_game_Player_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fxy.game.message.GameMessage.internal_static_game_Player_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fxy.game.message.Player.class, com.fxy.game.message.Player.Builder.class);
  }

  private int bitField0_;
  public static final int SESSIONID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>string sessionId = 1;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string sessionId = 1;</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int X_FIELD_NUMBER = 3;
  private int x_ = 0;
  /**
   * <code>int32 x = 3;</code>
   * @return The x.
   */
  @java.lang.Override
  public int getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 4;
  private int y_ = 0;
  /**
   * <code>int32 y = 4;</code>
   * @return The y.
   */
  @java.lang.Override
  public int getY() {
    return y_;
  }

  public static final int HP_FIELD_NUMBER = 5;
  private int hp_ = 0;
  /**
   * <code>int32 hp = 5;</code>
   * @return The hp.
   */
  @java.lang.Override
  public int getHp() {
    return hp_;
  }

  public static final int ATK_FIELD_NUMBER = 6;
  private int atk_ = 0;
  /**
   * <code>int32 atk = 6;</code>
   * @return The atk.
   */
  @java.lang.Override
  public int getAtk() {
    return atk_;
  }

  public static final int DFS_FIELD_NUMBER = 7;
  private int dfs_ = 0;
  /**
   * <code>int32 dfs = 7;</code>
   * @return The dfs.
   */
  @java.lang.Override
  public int getDfs() {
    return dfs_;
  }

  public static final int ROLE_FIELD_NUMBER = 8;
  private com.fxy.game.message.Role role_;
  /**
   * <code>.game.Role role = 8;</code>
   * @return Whether the role field is set.
   */
  @java.lang.Override
  public boolean hasRole() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.game.Role role = 8;</code>
   * @return The role.
   */
  @java.lang.Override
  public com.fxy.game.message.Role getRole() {
    return role_ == null ? com.fxy.game.message.Role.getDefaultInstance() : role_;
  }
  /**
   * <code>.game.Role role = 8;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.RoleOrBuilder getRoleOrBuilder() {
    return role_ == null ? com.fxy.game.message.Role.getDefaultInstance() : role_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionId_);
    }
    if (x_ != 0) {
      output.writeInt32(3, x_);
    }
    if (y_ != 0) {
      output.writeInt32(4, y_);
    }
    if (hp_ != 0) {
      output.writeInt32(5, hp_);
    }
    if (atk_ != 0) {
      output.writeInt32(6, atk_);
    }
    if (dfs_ != 0) {
      output.writeInt32(7, dfs_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(8, getRole());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionId_);
    }
    if (x_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, x_);
    }
    if (y_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, y_);
    }
    if (hp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, hp_);
    }
    if (atk_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, atk_);
    }
    if (dfs_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, dfs_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getRole());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fxy.game.message.Player)) {
      return super.equals(obj);
    }
    com.fxy.game.message.Player other = (com.fxy.game.message.Player) obj;

    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (getX()
        != other.getX()) return false;
    if (getY()
        != other.getY()) return false;
    if (getHp()
        != other.getHp()) return false;
    if (getAtk()
        != other.getAtk()) return false;
    if (getDfs()
        != other.getDfs()) return false;
    if (hasRole() != other.hasRole()) return false;
    if (hasRole()) {
      if (!getRole()
          .equals(other.getRole())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + getX();
    hash = (37 * hash) + Y_FIELD_NUMBER;
    hash = (53 * hash) + getY();
    hash = (37 * hash) + HP_FIELD_NUMBER;
    hash = (53 * hash) + getHp();
    hash = (37 * hash) + ATK_FIELD_NUMBER;
    hash = (53 * hash) + getAtk();
    hash = (37 * hash) + DFS_FIELD_NUMBER;
    hash = (53 * hash) + getDfs();
    if (hasRole()) {
      hash = (37 * hash) + ROLE_FIELD_NUMBER;
      hash = (53 * hash) + getRole().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fxy.game.message.Player parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fxy.game.message.Player parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fxy.game.message.Player parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fxy.game.message.Player parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fxy.game.message.Player parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fxy.game.message.Player parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fxy.game.message.Player parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.fxy.game.message.Player parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.fxy.game.message.Player parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.fxy.game.message.Player parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fxy.game.message.Player parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.fxy.game.message.Player parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fxy.game.message.Player prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code game.Player}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:game.Player)
      com.fxy.game.message.PlayerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fxy.game.message.GameMessage.internal_static_game_Player_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fxy.game.message.GameMessage.internal_static_game_Player_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fxy.game.message.Player.class, com.fxy.game.message.Player.Builder.class);
    }

    // Construct using com.fxy.game.message.Player.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRoleFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionId_ = "";
      x_ = 0;
      y_ = 0;
      hp_ = 0;
      atk_ = 0;
      dfs_ = 0;
      role_ = null;
      if (roleBuilder_ != null) {
        roleBuilder_.dispose();
        roleBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fxy.game.message.GameMessage.internal_static_game_Player_descriptor;
    }

    @java.lang.Override
    public com.fxy.game.message.Player getDefaultInstanceForType() {
      return com.fxy.game.message.Player.getDefaultInstance();
    }

    @java.lang.Override
    public com.fxy.game.message.Player build() {
      com.fxy.game.message.Player result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.fxy.game.message.Player buildPartial() {
      com.fxy.game.message.Player result = new com.fxy.game.message.Player(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.fxy.game.message.Player result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.x_ = x_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.y_ = y_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.hp_ = hp_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.atk_ = atk_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.dfs_ = dfs_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.role_ = roleBuilder_ == null
            ? role_
            : roleBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fxy.game.message.Player) {
        return mergeFrom((com.fxy.game.message.Player)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fxy.game.message.Player other) {
      if (other == com.fxy.game.message.Player.getDefaultInstance()) return this;
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getX() != 0) {
        setX(other.getX());
      }
      if (other.getY() != 0) {
        setY(other.getY());
      }
      if (other.getHp() != 0) {
        setHp(other.getHp());
      }
      if (other.getAtk() != 0) {
        setAtk(other.getAtk());
      }
      if (other.getDfs() != 0) {
        setDfs(other.getDfs());
      }
      if (other.hasRole()) {
        mergeRole(other.getRole());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 24: {
              x_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 24
            case 32: {
              y_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 32
            case 40: {
              hp_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 40
            case 48: {
              atk_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 48
            case 56: {
              dfs_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 56
            case 66: {
              input.readMessage(
                  internalGetRoleFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionId_ = "";
    /**
     * <code>string sessionId = 1;</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sessionId = 1;</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sessionId = 1;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string sessionId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string sessionId = 1;</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int x_ ;
    /**
     * <code>int32 x = 3;</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }
    /**
     * <code>int32 x = 3;</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(int value) {

      x_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 x = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      bitField0_ = (bitField0_ & ~0x00000002);
      x_ = 0;
      onChanged();
      return this;
    }

    private int y_ ;
    /**
     * <code>int32 y = 4;</code>
     * @return The y.
     */
    @java.lang.Override
    public int getY() {
      return y_;
    }
    /**
     * <code>int32 y = 4;</code>
     * @param value The y to set.
     * @return This builder for chaining.
     */
    public Builder setY(int value) {

      y_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 y = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearY() {
      bitField0_ = (bitField0_ & ~0x00000004);
      y_ = 0;
      onChanged();
      return this;
    }

    private int hp_ ;
    /**
     * <code>int32 hp = 5;</code>
     * @return The hp.
     */
    @java.lang.Override
    public int getHp() {
      return hp_;
    }
    /**
     * <code>int32 hp = 5;</code>
     * @param value The hp to set.
     * @return This builder for chaining.
     */
    public Builder setHp(int value) {

      hp_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 hp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearHp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      hp_ = 0;
      onChanged();
      return this;
    }

    private int atk_ ;
    /**
     * <code>int32 atk = 6;</code>
     * @return The atk.
     */
    @java.lang.Override
    public int getAtk() {
      return atk_;
    }
    /**
     * <code>int32 atk = 6;</code>
     * @param value The atk to set.
     * @return This builder for chaining.
     */
    public Builder setAtk(int value) {

      atk_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 atk = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAtk() {
      bitField0_ = (bitField0_ & ~0x00000010);
      atk_ = 0;
      onChanged();
      return this;
    }

    private int dfs_ ;
    /**
     * <code>int32 dfs = 7;</code>
     * @return The dfs.
     */
    @java.lang.Override
    public int getDfs() {
      return dfs_;
    }
    /**
     * <code>int32 dfs = 7;</code>
     * @param value The dfs to set.
     * @return This builder for chaining.
     */
    public Builder setDfs(int value) {

      dfs_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 dfs = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDfs() {
      bitField0_ = (bitField0_ & ~0x00000020);
      dfs_ = 0;
      onChanged();
      return this;
    }

    private com.fxy.game.message.Role role_;
    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.Role, com.fxy.game.message.Role.Builder, com.fxy.game.message.RoleOrBuilder> roleBuilder_;
    /**
     * <code>.game.Role role = 8;</code>
     * @return Whether the role field is set.
     */
    public boolean hasRole() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.game.Role role = 8;</code>
     * @return The role.
     */
    public com.fxy.game.message.Role getRole() {
      if (roleBuilder_ == null) {
        return role_ == null ? com.fxy.game.message.Role.getDefaultInstance() : role_;
      } else {
        return roleBuilder_.getMessage();
      }
    }
    /**
     * <code>.game.Role role = 8;</code>
     */
    public Builder setRole(com.fxy.game.message.Role value) {
      if (roleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        role_ = value;
      } else {
        roleBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.game.Role role = 8;</code>
     */
    public Builder setRole(
        com.fxy.game.message.Role.Builder builderForValue) {
      if (roleBuilder_ == null) {
        role_ = builderForValue.build();
      } else {
        roleBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.game.Role role = 8;</code>
     */
    public Builder mergeRole(com.fxy.game.message.Role value) {
      if (roleBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          role_ != null &&
          role_ != com.fxy.game.message.Role.getDefaultInstance()) {
          getRoleBuilder().mergeFrom(value);
        } else {
          role_ = value;
        }
      } else {
        roleBuilder_.mergeFrom(value);
      }
      if (role_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.game.Role role = 8;</code>
     */
    public Builder clearRole() {
      bitField0_ = (bitField0_ & ~0x00000040);
      role_ = null;
      if (roleBuilder_ != null) {
        roleBuilder_.dispose();
        roleBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.game.Role role = 8;</code>
     */
    public com.fxy.game.message.Role.Builder getRoleBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return internalGetRoleFieldBuilder().getBuilder();
    }
    /**
     * <code>.game.Role role = 8;</code>
     */
    public com.fxy.game.message.RoleOrBuilder getRoleOrBuilder() {
      if (roleBuilder_ != null) {
        return roleBuilder_.getMessageOrBuilder();
      } else {
        return role_ == null ?
            com.fxy.game.message.Role.getDefaultInstance() : role_;
      }
    }
    /**
     * <code>.game.Role role = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.Role, com.fxy.game.message.Role.Builder, com.fxy.game.message.RoleOrBuilder> 
        internalGetRoleFieldBuilder() {
      if (roleBuilder_ == null) {
        roleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.fxy.game.message.Role, com.fxy.game.message.Role.Builder, com.fxy.game.message.RoleOrBuilder>(
                getRole(),
                getParentForChildren(),
                isClean());
        role_ = null;
      }
      return roleBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:game.Player)
  }

  // @@protoc_insertion_point(class_scope:game.Player)
  private static final com.fxy.game.message.Player DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fxy.game.message.Player();
  }

  public static com.fxy.game.message.Player getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Player>
      PARSER = new com.google.protobuf.AbstractParser<Player>() {
    @java.lang.Override
    public Player parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Player> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Player> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.fxy.game.message.Player getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

