// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message_wrapper.proto
// Protobuf Java Version: 4.31.1

package com.fxy.game.message;

@com.google.protobuf.Generated
public interface RoleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.RoleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sessionId = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string sessionId = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>.game.RoleRequest.Op op = 2;</code>
   * @return The enum numeric value on the wire for op.
   */
  int getOpValue();
  /**
   * <code>.game.RoleRequest.Op op = 2;</code>
   * @return The op.
   */
  com.fxy.game.message.RoleRequest.Op getOp();

  /**
   * <code>string roleName = 3;</code>
   * @return The roleName.
   */
  java.lang.String getRoleName();
  /**
   * <code>string roleName = 3;</code>
   * @return The bytes for roleName.
   */
  com.google.protobuf.ByteString
      getRoleNameBytes();
}
