// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message_wrapper.proto
// Protobuf Java Version: 4.31.1

package com.fxy.game.message;

@com.google.protobuf.Generated
public interface RoleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.RoleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.game.Role role = 3;</code>
   * @return Whether the role field is set.
   */
  boolean hasRole();
  /**
   * <code>.game.Role role = 3;</code>
   * @return The role.
   */
  com.fxy.game.message.Role getRole();
  /**
   * <code>.game.Role role = 3;</code>
   */
  com.fxy.game.message.RoleOrBuilder getRoleOrBuilder();
}
