// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message_wrapper.proto
// Protobuf Java Version: 4.31.1

package com.fxy.game.message;

@com.google.protobuf.Generated
public interface WrapperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.Wrapper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.game.AuthRequest authRequest = 1;</code>
   * @return Whether the authRequest field is set.
   */
  boolean hasAuthRequest();
  /**
   * <code>.game.AuthRequest authRequest = 1;</code>
   * @return The authRequest.
   */
  com.fxy.game.message.AuthRequest getAuthRequest();
  /**
   * <code>.game.AuthRequest authRequest = 1;</code>
   */
  com.fxy.game.message.AuthRequestOrBuilder getAuthRequestOrBuilder();

  /**
   * <code>.game.AuthResponse authResponse = 2;</code>
   * @return Whether the authResponse field is set.
   */
  boolean hasAuthResponse();
  /**
   * <code>.game.AuthResponse authResponse = 2;</code>
   * @return The authResponse.
   */
  com.fxy.game.message.AuthResponse getAuthResponse();
  /**
   * <code>.game.AuthResponse authResponse = 2;</code>
   */
  com.fxy.game.message.AuthResponseOrBuilder getAuthResponseOrBuilder();

  /**
   * <code>.game.ChatRequest chatRequest = 3;</code>
   * @return Whether the chatRequest field is set.
   */
  boolean hasChatRequest();
  /**
   * <code>.game.ChatRequest chatRequest = 3;</code>
   * @return The chatRequest.
   */
  com.fxy.game.message.ChatRequest getChatRequest();
  /**
   * <code>.game.ChatRequest chatRequest = 3;</code>
   */
  com.fxy.game.message.ChatRequestOrBuilder getChatRequestOrBuilder();

  /**
   * <code>.game.ChatResponse chatResponse = 4;</code>
   * @return Whether the chatResponse field is set.
   */
  boolean hasChatResponse();
  /**
   * <code>.game.ChatResponse chatResponse = 4;</code>
   * @return The chatResponse.
   */
  com.fxy.game.message.ChatResponse getChatResponse();
  /**
   * <code>.game.ChatResponse chatResponse = 4;</code>
   */
  com.fxy.game.message.ChatResponseOrBuilder getChatResponseOrBuilder();

  /**
   * <code>.game.GameAction gameAction = 5;</code>
   * @return Whether the gameAction field is set.
   */
  boolean hasGameAction();
  /**
   * <code>.game.GameAction gameAction = 5;</code>
   * @return The gameAction.
   */
  com.fxy.game.message.GameAction getGameAction();
  /**
   * <code>.game.GameAction gameAction = 5;</code>
   */
  com.fxy.game.message.GameActionOrBuilder getGameActionOrBuilder();

  /**
   * <code>.game.GameState gameState = 6;</code>
   * @return Whether the gameState field is set.
   */
  boolean hasGameState();
  /**
   * <code>.game.GameState gameState = 6;</code>
   * @return The gameState.
   */
  com.fxy.game.message.GameState getGameState();
  /**
   * <code>.game.GameState gameState = 6;</code>
   */
  com.fxy.game.message.GameStateOrBuilder getGameStateOrBuilder();

  /**
   * <code>.game.ShopRequest shopRequest = 7;</code>
   * @return Whether the shopRequest field is set.
   */
  boolean hasShopRequest();
  /**
   * <code>.game.ShopRequest shopRequest = 7;</code>
   * @return The shopRequest.
   */
  com.fxy.game.message.ShopRequest getShopRequest();
  /**
   * <code>.game.ShopRequest shopRequest = 7;</code>
   */
  com.fxy.game.message.ShopRequestOrBuilder getShopRequestOrBuilder();

  /**
   * <code>.game.ShopResponse shopResponse = 8;</code>
   * @return Whether the shopResponse field is set.
   */
  boolean hasShopResponse();
  /**
   * <code>.game.ShopResponse shopResponse = 8;</code>
   * @return The shopResponse.
   */
  com.fxy.game.message.ShopResponse getShopResponse();
  /**
   * <code>.game.ShopResponse shopResponse = 8;</code>
   */
  com.fxy.game.message.ShopResponseOrBuilder getShopResponseOrBuilder();

  /**
   * <code>.game.MailRequest mailRequest = 9;</code>
   * @return Whether the mailRequest field is set.
   */
  boolean hasMailRequest();
  /**
   * <code>.game.MailRequest mailRequest = 9;</code>
   * @return The mailRequest.
   */
  com.fxy.game.message.MailRequest getMailRequest();
  /**
   * <code>.game.MailRequest mailRequest = 9;</code>
   */
  com.fxy.game.message.MailRequestOrBuilder getMailRequestOrBuilder();

  /**
   * <code>.game.MailResponse mailResponse = 10;</code>
   * @return Whether the mailResponse field is set.
   */
  boolean hasMailResponse();
  /**
   * <code>.game.MailResponse mailResponse = 10;</code>
   * @return The mailResponse.
   */
  com.fxy.game.message.MailResponse getMailResponse();
  /**
   * <code>.game.MailResponse mailResponse = 10;</code>
   */
  com.fxy.game.message.MailResponseOrBuilder getMailResponseOrBuilder();

  /**
   * <code>.game.RoleRequest roleRequest = 11;</code>
   * @return Whether the roleRequest field is set.
   */
  boolean hasRoleRequest();
  /**
   * <code>.game.RoleRequest roleRequest = 11;</code>
   * @return The roleRequest.
   */
  com.fxy.game.message.RoleRequest getRoleRequest();
  /**
   * <code>.game.RoleRequest roleRequest = 11;</code>
   */
  com.fxy.game.message.RoleRequestOrBuilder getRoleRequestOrBuilder();

  /**
   * <code>.game.RoleResponse roleResponse = 12;</code>
   * @return Whether the roleResponse field is set.
   */
  boolean hasRoleResponse();
  /**
   * <code>.game.RoleResponse roleResponse = 12;</code>
   * @return The roleResponse.
   */
  com.fxy.game.message.RoleResponse getRoleResponse();
  /**
   * <code>.game.RoleResponse roleResponse = 12;</code>
   */
  com.fxy.game.message.RoleResponseOrBuilder getRoleResponseOrBuilder();

  com.fxy.game.message.Wrapper.MsgCase getMsgCase();
}
