// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message_wrapper.proto
// Protobuf Java Version: 4.31.1

package com.fxy.game.message;

/**
 * Protobuf type {@code game.Wrapper}
 */
@com.google.protobuf.Generated
public final class Wrapper extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:game.Wrapper)
    WrapperOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Wrapper.class.getName());
  }
  // Use Wrapper.newBuilder() to construct.
  private Wrapper(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Wrapper() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fxy.game.message.GameMessage.internal_static_game_Wrapper_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fxy.game.message.GameMessage.internal_static_game_Wrapper_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fxy.game.message.Wrapper.class, com.fxy.game.message.Wrapper.Builder.class);
  }

  private int msgCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object msg_;
  public enum MsgCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    AUTHREQUEST(1),
    AUTHRESPONSE(2),
    CHATREQUEST(3),
    CHATRESPONSE(4),
    GAMEACTION(5),
    GAMESTATE(6),
    SHOPREQUEST(7),
    SHOPRESPONSE(8),
    MAILREQUEST(9),
    MAILRESPONSE(10),
    ROLEREQUEST(11),
    ROLERESPONSE(12),
    MSG_NOT_SET(0);
    private final int value;
    private MsgCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCase valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCase forNumber(int value) {
      switch (value) {
        case 1: return AUTHREQUEST;
        case 2: return AUTHRESPONSE;
        case 3: return CHATREQUEST;
        case 4: return CHATRESPONSE;
        case 5: return GAMEACTION;
        case 6: return GAMESTATE;
        case 7: return SHOPREQUEST;
        case 8: return SHOPRESPONSE;
        case 9: return MAILREQUEST;
        case 10: return MAILRESPONSE;
        case 11: return ROLEREQUEST;
        case 12: return ROLERESPONSE;
        case 0: return MSG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MsgCase
  getMsgCase() {
    return MsgCase.forNumber(
        msgCase_);
  }

  public static final int AUTHREQUEST_FIELD_NUMBER = 1;
  /**
   * <code>.game.AuthRequest authRequest = 1;</code>
   * @return Whether the authRequest field is set.
   */
  @java.lang.Override
  public boolean hasAuthRequest() {
    return msgCase_ == 1;
  }
  /**
   * <code>.game.AuthRequest authRequest = 1;</code>
   * @return The authRequest.
   */
  @java.lang.Override
  public com.fxy.game.message.AuthRequest getAuthRequest() {
    if (msgCase_ == 1) {
       return (com.fxy.game.message.AuthRequest) msg_;
    }
    return com.fxy.game.message.AuthRequest.getDefaultInstance();
  }
  /**
   * <code>.game.AuthRequest authRequest = 1;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.AuthRequestOrBuilder getAuthRequestOrBuilder() {
    if (msgCase_ == 1) {
       return (com.fxy.game.message.AuthRequest) msg_;
    }
    return com.fxy.game.message.AuthRequest.getDefaultInstance();
  }

  public static final int AUTHRESPONSE_FIELD_NUMBER = 2;
  /**
   * <code>.game.AuthResponse authResponse = 2;</code>
   * @return Whether the authResponse field is set.
   */
  @java.lang.Override
  public boolean hasAuthResponse() {
    return msgCase_ == 2;
  }
  /**
   * <code>.game.AuthResponse authResponse = 2;</code>
   * @return The authResponse.
   */
  @java.lang.Override
  public com.fxy.game.message.AuthResponse getAuthResponse() {
    if (msgCase_ == 2) {
       return (com.fxy.game.message.AuthResponse) msg_;
    }
    return com.fxy.game.message.AuthResponse.getDefaultInstance();
  }
  /**
   * <code>.game.AuthResponse authResponse = 2;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.AuthResponseOrBuilder getAuthResponseOrBuilder() {
    if (msgCase_ == 2) {
       return (com.fxy.game.message.AuthResponse) msg_;
    }
    return com.fxy.game.message.AuthResponse.getDefaultInstance();
  }

  public static final int CHATREQUEST_FIELD_NUMBER = 3;
  /**
   * <code>.game.ChatRequest chatRequest = 3;</code>
   * @return Whether the chatRequest field is set.
   */
  @java.lang.Override
  public boolean hasChatRequest() {
    return msgCase_ == 3;
  }
  /**
   * <code>.game.ChatRequest chatRequest = 3;</code>
   * @return The chatRequest.
   */
  @java.lang.Override
  public com.fxy.game.message.ChatRequest getChatRequest() {
    if (msgCase_ == 3) {
       return (com.fxy.game.message.ChatRequest) msg_;
    }
    return com.fxy.game.message.ChatRequest.getDefaultInstance();
  }
  /**
   * <code>.game.ChatRequest chatRequest = 3;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.ChatRequestOrBuilder getChatRequestOrBuilder() {
    if (msgCase_ == 3) {
       return (com.fxy.game.message.ChatRequest) msg_;
    }
    return com.fxy.game.message.ChatRequest.getDefaultInstance();
  }

  public static final int CHATRESPONSE_FIELD_NUMBER = 4;
  /**
   * <code>.game.ChatResponse chatResponse = 4;</code>
   * @return Whether the chatResponse field is set.
   */
  @java.lang.Override
  public boolean hasChatResponse() {
    return msgCase_ == 4;
  }
  /**
   * <code>.game.ChatResponse chatResponse = 4;</code>
   * @return The chatResponse.
   */
  @java.lang.Override
  public com.fxy.game.message.ChatResponse getChatResponse() {
    if (msgCase_ == 4) {
       return (com.fxy.game.message.ChatResponse) msg_;
    }
    return com.fxy.game.message.ChatResponse.getDefaultInstance();
  }
  /**
   * <code>.game.ChatResponse chatResponse = 4;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.ChatResponseOrBuilder getChatResponseOrBuilder() {
    if (msgCase_ == 4) {
       return (com.fxy.game.message.ChatResponse) msg_;
    }
    return com.fxy.game.message.ChatResponse.getDefaultInstance();
  }

  public static final int GAMEACTION_FIELD_NUMBER = 5;
  /**
   * <code>.game.GameAction gameAction = 5;</code>
   * @return Whether the gameAction field is set.
   */
  @java.lang.Override
  public boolean hasGameAction() {
    return msgCase_ == 5;
  }
  /**
   * <code>.game.GameAction gameAction = 5;</code>
   * @return The gameAction.
   */
  @java.lang.Override
  public com.fxy.game.message.GameAction getGameAction() {
    if (msgCase_ == 5) {
       return (com.fxy.game.message.GameAction) msg_;
    }
    return com.fxy.game.message.GameAction.getDefaultInstance();
  }
  /**
   * <code>.game.GameAction gameAction = 5;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.GameActionOrBuilder getGameActionOrBuilder() {
    if (msgCase_ == 5) {
       return (com.fxy.game.message.GameAction) msg_;
    }
    return com.fxy.game.message.GameAction.getDefaultInstance();
  }

  public static final int GAMESTATE_FIELD_NUMBER = 6;
  /**
   * <code>.game.GameState gameState = 6;</code>
   * @return Whether the gameState field is set.
   */
  @java.lang.Override
  public boolean hasGameState() {
    return msgCase_ == 6;
  }
  /**
   * <code>.game.GameState gameState = 6;</code>
   * @return The gameState.
   */
  @java.lang.Override
  public com.fxy.game.message.GameState getGameState() {
    if (msgCase_ == 6) {
       return (com.fxy.game.message.GameState) msg_;
    }
    return com.fxy.game.message.GameState.getDefaultInstance();
  }
  /**
   * <code>.game.GameState gameState = 6;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.GameStateOrBuilder getGameStateOrBuilder() {
    if (msgCase_ == 6) {
       return (com.fxy.game.message.GameState) msg_;
    }
    return com.fxy.game.message.GameState.getDefaultInstance();
  }

  public static final int SHOPREQUEST_FIELD_NUMBER = 7;
  /**
   * <code>.game.ShopRequest shopRequest = 7;</code>
   * @return Whether the shopRequest field is set.
   */
  @java.lang.Override
  public boolean hasShopRequest() {
    return msgCase_ == 7;
  }
  /**
   * <code>.game.ShopRequest shopRequest = 7;</code>
   * @return The shopRequest.
   */
  @java.lang.Override
  public com.fxy.game.message.ShopRequest getShopRequest() {
    if (msgCase_ == 7) {
       return (com.fxy.game.message.ShopRequest) msg_;
    }
    return com.fxy.game.message.ShopRequest.getDefaultInstance();
  }
  /**
   * <code>.game.ShopRequest shopRequest = 7;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.ShopRequestOrBuilder getShopRequestOrBuilder() {
    if (msgCase_ == 7) {
       return (com.fxy.game.message.ShopRequest) msg_;
    }
    return com.fxy.game.message.ShopRequest.getDefaultInstance();
  }

  public static final int SHOPRESPONSE_FIELD_NUMBER = 8;
  /**
   * <code>.game.ShopResponse shopResponse = 8;</code>
   * @return Whether the shopResponse field is set.
   */
  @java.lang.Override
  public boolean hasShopResponse() {
    return msgCase_ == 8;
  }
  /**
   * <code>.game.ShopResponse shopResponse = 8;</code>
   * @return The shopResponse.
   */
  @java.lang.Override
  public com.fxy.game.message.ShopResponse getShopResponse() {
    if (msgCase_ == 8) {
       return (com.fxy.game.message.ShopResponse) msg_;
    }
    return com.fxy.game.message.ShopResponse.getDefaultInstance();
  }
  /**
   * <code>.game.ShopResponse shopResponse = 8;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.ShopResponseOrBuilder getShopResponseOrBuilder() {
    if (msgCase_ == 8) {
       return (com.fxy.game.message.ShopResponse) msg_;
    }
    return com.fxy.game.message.ShopResponse.getDefaultInstance();
  }

  public static final int MAILREQUEST_FIELD_NUMBER = 9;
  /**
   * <code>.game.MailRequest mailRequest = 9;</code>
   * @return Whether the mailRequest field is set.
   */
  @java.lang.Override
  public boolean hasMailRequest() {
    return msgCase_ == 9;
  }
  /**
   * <code>.game.MailRequest mailRequest = 9;</code>
   * @return The mailRequest.
   */
  @java.lang.Override
  public com.fxy.game.message.MailRequest getMailRequest() {
    if (msgCase_ == 9) {
       return (com.fxy.game.message.MailRequest) msg_;
    }
    return com.fxy.game.message.MailRequest.getDefaultInstance();
  }
  /**
   * <code>.game.MailRequest mailRequest = 9;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.MailRequestOrBuilder getMailRequestOrBuilder() {
    if (msgCase_ == 9) {
       return (com.fxy.game.message.MailRequest) msg_;
    }
    return com.fxy.game.message.MailRequest.getDefaultInstance();
  }

  public static final int MAILRESPONSE_FIELD_NUMBER = 10;
  /**
   * <code>.game.MailResponse mailResponse = 10;</code>
   * @return Whether the mailResponse field is set.
   */
  @java.lang.Override
  public boolean hasMailResponse() {
    return msgCase_ == 10;
  }
  /**
   * <code>.game.MailResponse mailResponse = 10;</code>
   * @return The mailResponse.
   */
  @java.lang.Override
  public com.fxy.game.message.MailResponse getMailResponse() {
    if (msgCase_ == 10) {
       return (com.fxy.game.message.MailResponse) msg_;
    }
    return com.fxy.game.message.MailResponse.getDefaultInstance();
  }
  /**
   * <code>.game.MailResponse mailResponse = 10;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.MailResponseOrBuilder getMailResponseOrBuilder() {
    if (msgCase_ == 10) {
       return (com.fxy.game.message.MailResponse) msg_;
    }
    return com.fxy.game.message.MailResponse.getDefaultInstance();
  }

  public static final int ROLEREQUEST_FIELD_NUMBER = 11;
  /**
   * <code>.game.RoleRequest roleRequest = 11;</code>
   * @return Whether the roleRequest field is set.
   */
  @java.lang.Override
  public boolean hasRoleRequest() {
    return msgCase_ == 11;
  }
  /**
   * <code>.game.RoleRequest roleRequest = 11;</code>
   * @return The roleRequest.
   */
  @java.lang.Override
  public com.fxy.game.message.RoleRequest getRoleRequest() {
    if (msgCase_ == 11) {
       return (com.fxy.game.message.RoleRequest) msg_;
    }
    return com.fxy.game.message.RoleRequest.getDefaultInstance();
  }
  /**
   * <code>.game.RoleRequest roleRequest = 11;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.RoleRequestOrBuilder getRoleRequestOrBuilder() {
    if (msgCase_ == 11) {
       return (com.fxy.game.message.RoleRequest) msg_;
    }
    return com.fxy.game.message.RoleRequest.getDefaultInstance();
  }

  public static final int ROLERESPONSE_FIELD_NUMBER = 12;
  /**
   * <code>.game.RoleResponse roleResponse = 12;</code>
   * @return Whether the roleResponse field is set.
   */
  @java.lang.Override
  public boolean hasRoleResponse() {
    return msgCase_ == 12;
  }
  /**
   * <code>.game.RoleResponse roleResponse = 12;</code>
   * @return The roleResponse.
   */
  @java.lang.Override
  public com.fxy.game.message.RoleResponse getRoleResponse() {
    if (msgCase_ == 12) {
       return (com.fxy.game.message.RoleResponse) msg_;
    }
    return com.fxy.game.message.RoleResponse.getDefaultInstance();
  }
  /**
   * <code>.game.RoleResponse roleResponse = 12;</code>
   */
  @java.lang.Override
  public com.fxy.game.message.RoleResponseOrBuilder getRoleResponseOrBuilder() {
    if (msgCase_ == 12) {
       return (com.fxy.game.message.RoleResponse) msg_;
    }
    return com.fxy.game.message.RoleResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (msgCase_ == 1) {
      output.writeMessage(1, (com.fxy.game.message.AuthRequest) msg_);
    }
    if (msgCase_ == 2) {
      output.writeMessage(2, (com.fxy.game.message.AuthResponse) msg_);
    }
    if (msgCase_ == 3) {
      output.writeMessage(3, (com.fxy.game.message.ChatRequest) msg_);
    }
    if (msgCase_ == 4) {
      output.writeMessage(4, (com.fxy.game.message.ChatResponse) msg_);
    }
    if (msgCase_ == 5) {
      output.writeMessage(5, (com.fxy.game.message.GameAction) msg_);
    }
    if (msgCase_ == 6) {
      output.writeMessage(6, (com.fxy.game.message.GameState) msg_);
    }
    if (msgCase_ == 7) {
      output.writeMessage(7, (com.fxy.game.message.ShopRequest) msg_);
    }
    if (msgCase_ == 8) {
      output.writeMessage(8, (com.fxy.game.message.ShopResponse) msg_);
    }
    if (msgCase_ == 9) {
      output.writeMessage(9, (com.fxy.game.message.MailRequest) msg_);
    }
    if (msgCase_ == 10) {
      output.writeMessage(10, (com.fxy.game.message.MailResponse) msg_);
    }
    if (msgCase_ == 11) {
      output.writeMessage(11, (com.fxy.game.message.RoleRequest) msg_);
    }
    if (msgCase_ == 12) {
      output.writeMessage(12, (com.fxy.game.message.RoleResponse) msg_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (msgCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.fxy.game.message.AuthRequest) msg_);
    }
    if (msgCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.fxy.game.message.AuthResponse) msg_);
    }
    if (msgCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.fxy.game.message.ChatRequest) msg_);
    }
    if (msgCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.fxy.game.message.ChatResponse) msg_);
    }
    if (msgCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.fxy.game.message.GameAction) msg_);
    }
    if (msgCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.fxy.game.message.GameState) msg_);
    }
    if (msgCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (com.fxy.game.message.ShopRequest) msg_);
    }
    if (msgCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (com.fxy.game.message.ShopResponse) msg_);
    }
    if (msgCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, (com.fxy.game.message.MailRequest) msg_);
    }
    if (msgCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, (com.fxy.game.message.MailResponse) msg_);
    }
    if (msgCase_ == 11) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, (com.fxy.game.message.RoleRequest) msg_);
    }
    if (msgCase_ == 12) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, (com.fxy.game.message.RoleResponse) msg_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fxy.game.message.Wrapper)) {
      return super.equals(obj);
    }
    com.fxy.game.message.Wrapper other = (com.fxy.game.message.Wrapper) obj;

    if (!getMsgCase().equals(other.getMsgCase())) return false;
    switch (msgCase_) {
      case 1:
        if (!getAuthRequest()
            .equals(other.getAuthRequest())) return false;
        break;
      case 2:
        if (!getAuthResponse()
            .equals(other.getAuthResponse())) return false;
        break;
      case 3:
        if (!getChatRequest()
            .equals(other.getChatRequest())) return false;
        break;
      case 4:
        if (!getChatResponse()
            .equals(other.getChatResponse())) return false;
        break;
      case 5:
        if (!getGameAction()
            .equals(other.getGameAction())) return false;
        break;
      case 6:
        if (!getGameState()
            .equals(other.getGameState())) return false;
        break;
      case 7:
        if (!getShopRequest()
            .equals(other.getShopRequest())) return false;
        break;
      case 8:
        if (!getShopResponse()
            .equals(other.getShopResponse())) return false;
        break;
      case 9:
        if (!getMailRequest()
            .equals(other.getMailRequest())) return false;
        break;
      case 10:
        if (!getMailResponse()
            .equals(other.getMailResponse())) return false;
        break;
      case 11:
        if (!getRoleRequest()
            .equals(other.getRoleRequest())) return false;
        break;
      case 12:
        if (!getRoleResponse()
            .equals(other.getRoleResponse())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (msgCase_) {
      case 1:
        hash = (37 * hash) + AUTHREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getAuthRequest().hashCode();
        break;
      case 2:
        hash = (37 * hash) + AUTHRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getAuthResponse().hashCode();
        break;
      case 3:
        hash = (37 * hash) + CHATREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getChatRequest().hashCode();
        break;
      case 4:
        hash = (37 * hash) + CHATRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getChatResponse().hashCode();
        break;
      case 5:
        hash = (37 * hash) + GAMEACTION_FIELD_NUMBER;
        hash = (53 * hash) + getGameAction().hashCode();
        break;
      case 6:
        hash = (37 * hash) + GAMESTATE_FIELD_NUMBER;
        hash = (53 * hash) + getGameState().hashCode();
        break;
      case 7:
        hash = (37 * hash) + SHOPREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getShopRequest().hashCode();
        break;
      case 8:
        hash = (37 * hash) + SHOPRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getShopResponse().hashCode();
        break;
      case 9:
        hash = (37 * hash) + MAILREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getMailRequest().hashCode();
        break;
      case 10:
        hash = (37 * hash) + MAILRESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getMailResponse().hashCode();
        break;
      case 11:
        hash = (37 * hash) + ROLEREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRoleRequest().hashCode();
        break;
      case 12:
        hash = (37 * hash) + ROLERESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getRoleResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fxy.game.message.Wrapper parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fxy.game.message.Wrapper parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fxy.game.message.Wrapper parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fxy.game.message.Wrapper parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fxy.game.message.Wrapper parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fxy.game.message.Wrapper parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fxy.game.message.Wrapper parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.fxy.game.message.Wrapper parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.fxy.game.message.Wrapper parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.fxy.game.message.Wrapper parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fxy.game.message.Wrapper parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.fxy.game.message.Wrapper parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fxy.game.message.Wrapper prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code game.Wrapper}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:game.Wrapper)
      com.fxy.game.message.WrapperOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fxy.game.message.GameMessage.internal_static_game_Wrapper_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fxy.game.message.GameMessage.internal_static_game_Wrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fxy.game.message.Wrapper.class, com.fxy.game.message.Wrapper.Builder.class);
    }

    // Construct using com.fxy.game.message.Wrapper.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (authRequestBuilder_ != null) {
        authRequestBuilder_.clear();
      }
      if (authResponseBuilder_ != null) {
        authResponseBuilder_.clear();
      }
      if (chatRequestBuilder_ != null) {
        chatRequestBuilder_.clear();
      }
      if (chatResponseBuilder_ != null) {
        chatResponseBuilder_.clear();
      }
      if (gameActionBuilder_ != null) {
        gameActionBuilder_.clear();
      }
      if (gameStateBuilder_ != null) {
        gameStateBuilder_.clear();
      }
      if (shopRequestBuilder_ != null) {
        shopRequestBuilder_.clear();
      }
      if (shopResponseBuilder_ != null) {
        shopResponseBuilder_.clear();
      }
      if (mailRequestBuilder_ != null) {
        mailRequestBuilder_.clear();
      }
      if (mailResponseBuilder_ != null) {
        mailResponseBuilder_.clear();
      }
      if (roleRequestBuilder_ != null) {
        roleRequestBuilder_.clear();
      }
      if (roleResponseBuilder_ != null) {
        roleResponseBuilder_.clear();
      }
      msgCase_ = 0;
      msg_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fxy.game.message.GameMessage.internal_static_game_Wrapper_descriptor;
    }

    @java.lang.Override
    public com.fxy.game.message.Wrapper getDefaultInstanceForType() {
      return com.fxy.game.message.Wrapper.getDefaultInstance();
    }

    @java.lang.Override
    public com.fxy.game.message.Wrapper build() {
      com.fxy.game.message.Wrapper result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.fxy.game.message.Wrapper buildPartial() {
      com.fxy.game.message.Wrapper result = new com.fxy.game.message.Wrapper(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.fxy.game.message.Wrapper result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.fxy.game.message.Wrapper result) {
      result.msgCase_ = msgCase_;
      result.msg_ = this.msg_;
      if (msgCase_ == 1 &&
          authRequestBuilder_ != null) {
        result.msg_ = authRequestBuilder_.build();
      }
      if (msgCase_ == 2 &&
          authResponseBuilder_ != null) {
        result.msg_ = authResponseBuilder_.build();
      }
      if (msgCase_ == 3 &&
          chatRequestBuilder_ != null) {
        result.msg_ = chatRequestBuilder_.build();
      }
      if (msgCase_ == 4 &&
          chatResponseBuilder_ != null) {
        result.msg_ = chatResponseBuilder_.build();
      }
      if (msgCase_ == 5 &&
          gameActionBuilder_ != null) {
        result.msg_ = gameActionBuilder_.build();
      }
      if (msgCase_ == 6 &&
          gameStateBuilder_ != null) {
        result.msg_ = gameStateBuilder_.build();
      }
      if (msgCase_ == 7 &&
          shopRequestBuilder_ != null) {
        result.msg_ = shopRequestBuilder_.build();
      }
      if (msgCase_ == 8 &&
          shopResponseBuilder_ != null) {
        result.msg_ = shopResponseBuilder_.build();
      }
      if (msgCase_ == 9 &&
          mailRequestBuilder_ != null) {
        result.msg_ = mailRequestBuilder_.build();
      }
      if (msgCase_ == 10 &&
          mailResponseBuilder_ != null) {
        result.msg_ = mailResponseBuilder_.build();
      }
      if (msgCase_ == 11 &&
          roleRequestBuilder_ != null) {
        result.msg_ = roleRequestBuilder_.build();
      }
      if (msgCase_ == 12 &&
          roleResponseBuilder_ != null) {
        result.msg_ = roleResponseBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fxy.game.message.Wrapper) {
        return mergeFrom((com.fxy.game.message.Wrapper)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fxy.game.message.Wrapper other) {
      if (other == com.fxy.game.message.Wrapper.getDefaultInstance()) return this;
      switch (other.getMsgCase()) {
        case AUTHREQUEST: {
          mergeAuthRequest(other.getAuthRequest());
          break;
        }
        case AUTHRESPONSE: {
          mergeAuthResponse(other.getAuthResponse());
          break;
        }
        case CHATREQUEST: {
          mergeChatRequest(other.getChatRequest());
          break;
        }
        case CHATRESPONSE: {
          mergeChatResponse(other.getChatResponse());
          break;
        }
        case GAMEACTION: {
          mergeGameAction(other.getGameAction());
          break;
        }
        case GAMESTATE: {
          mergeGameState(other.getGameState());
          break;
        }
        case SHOPREQUEST: {
          mergeShopRequest(other.getShopRequest());
          break;
        }
        case SHOPRESPONSE: {
          mergeShopResponse(other.getShopResponse());
          break;
        }
        case MAILREQUEST: {
          mergeMailRequest(other.getMailRequest());
          break;
        }
        case MAILRESPONSE: {
          mergeMailResponse(other.getMailResponse());
          break;
        }
        case ROLEREQUEST: {
          mergeRoleRequest(other.getRoleRequest());
          break;
        }
        case ROLERESPONSE: {
          mergeRoleResponse(other.getRoleResponse());
          break;
        }
        case MSG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetAuthRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetAuthResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetChatRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetChatResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetGameActionFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetGameStateFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 6;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  internalGetShopRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 7;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  internalGetShopResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 8;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  internalGetMailRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 9;
              break;
            } // case 74
            case 82: {
              input.readMessage(
                  internalGetMailResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 10;
              break;
            } // case 82
            case 90: {
              input.readMessage(
                  internalGetRoleRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 11;
              break;
            } // case 90
            case 98: {
              input.readMessage(
                  internalGetRoleResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 12;
              break;
            } // case 98
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public MsgCase
        getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public Builder clearMsg() {
      msgCase_ = 0;
      msg_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.AuthRequest, com.fxy.game.message.AuthRequest.Builder, com.fxy.game.message.AuthRequestOrBuilder> authRequestBuilder_;
    /**
     * <code>.game.AuthRequest authRequest = 1;</code>
     * @return Whether the authRequest field is set.
     */
    @java.lang.Override
    public boolean hasAuthRequest() {
      return msgCase_ == 1;
    }
    /**
     * <code>.game.AuthRequest authRequest = 1;</code>
     * @return The authRequest.
     */
    @java.lang.Override
    public com.fxy.game.message.AuthRequest getAuthRequest() {
      if (authRequestBuilder_ == null) {
        if (msgCase_ == 1) {
          return (com.fxy.game.message.AuthRequest) msg_;
        }
        return com.fxy.game.message.AuthRequest.getDefaultInstance();
      } else {
        if (msgCase_ == 1) {
          return authRequestBuilder_.getMessage();
        }
        return com.fxy.game.message.AuthRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.game.AuthRequest authRequest = 1;</code>
     */
    public Builder setAuthRequest(com.fxy.game.message.AuthRequest value) {
      if (authRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        authRequestBuilder_.setMessage(value);
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.game.AuthRequest authRequest = 1;</code>
     */
    public Builder setAuthRequest(
        com.fxy.game.message.AuthRequest.Builder builderForValue) {
      if (authRequestBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        authRequestBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.game.AuthRequest authRequest = 1;</code>
     */
    public Builder mergeAuthRequest(com.fxy.game.message.AuthRequest value) {
      if (authRequestBuilder_ == null) {
        if (msgCase_ == 1 &&
            msg_ != com.fxy.game.message.AuthRequest.getDefaultInstance()) {
          msg_ = com.fxy.game.message.AuthRequest.newBuilder((com.fxy.game.message.AuthRequest) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 1) {
          authRequestBuilder_.mergeFrom(value);
        } else {
          authRequestBuilder_.setMessage(value);
        }
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.game.AuthRequest authRequest = 1;</code>
     */
    public Builder clearAuthRequest() {
      if (authRequestBuilder_ == null) {
        if (msgCase_ == 1) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 1) {
          msgCase_ = 0;
          msg_ = null;
        }
        authRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.game.AuthRequest authRequest = 1;</code>
     */
    public com.fxy.game.message.AuthRequest.Builder getAuthRequestBuilder() {
      return internalGetAuthRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.game.AuthRequest authRequest = 1;</code>
     */
    @java.lang.Override
    public com.fxy.game.message.AuthRequestOrBuilder getAuthRequestOrBuilder() {
      if ((msgCase_ == 1) && (authRequestBuilder_ != null)) {
        return authRequestBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 1) {
          return (com.fxy.game.message.AuthRequest) msg_;
        }
        return com.fxy.game.message.AuthRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.game.AuthRequest authRequest = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.AuthRequest, com.fxy.game.message.AuthRequest.Builder, com.fxy.game.message.AuthRequestOrBuilder> 
        internalGetAuthRequestFieldBuilder() {
      if (authRequestBuilder_ == null) {
        if (!(msgCase_ == 1)) {
          msg_ = com.fxy.game.message.AuthRequest.getDefaultInstance();
        }
        authRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.fxy.game.message.AuthRequest, com.fxy.game.message.AuthRequest.Builder, com.fxy.game.message.AuthRequestOrBuilder>(
                (com.fxy.game.message.AuthRequest) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 1;
      onChanged();
      return authRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.AuthResponse, com.fxy.game.message.AuthResponse.Builder, com.fxy.game.message.AuthResponseOrBuilder> authResponseBuilder_;
    /**
     * <code>.game.AuthResponse authResponse = 2;</code>
     * @return Whether the authResponse field is set.
     */
    @java.lang.Override
    public boolean hasAuthResponse() {
      return msgCase_ == 2;
    }
    /**
     * <code>.game.AuthResponse authResponse = 2;</code>
     * @return The authResponse.
     */
    @java.lang.Override
    public com.fxy.game.message.AuthResponse getAuthResponse() {
      if (authResponseBuilder_ == null) {
        if (msgCase_ == 2) {
          return (com.fxy.game.message.AuthResponse) msg_;
        }
        return com.fxy.game.message.AuthResponse.getDefaultInstance();
      } else {
        if (msgCase_ == 2) {
          return authResponseBuilder_.getMessage();
        }
        return com.fxy.game.message.AuthResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.game.AuthResponse authResponse = 2;</code>
     */
    public Builder setAuthResponse(com.fxy.game.message.AuthResponse value) {
      if (authResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        authResponseBuilder_.setMessage(value);
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.game.AuthResponse authResponse = 2;</code>
     */
    public Builder setAuthResponse(
        com.fxy.game.message.AuthResponse.Builder builderForValue) {
      if (authResponseBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        authResponseBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.game.AuthResponse authResponse = 2;</code>
     */
    public Builder mergeAuthResponse(com.fxy.game.message.AuthResponse value) {
      if (authResponseBuilder_ == null) {
        if (msgCase_ == 2 &&
            msg_ != com.fxy.game.message.AuthResponse.getDefaultInstance()) {
          msg_ = com.fxy.game.message.AuthResponse.newBuilder((com.fxy.game.message.AuthResponse) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 2) {
          authResponseBuilder_.mergeFrom(value);
        } else {
          authResponseBuilder_.setMessage(value);
        }
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.game.AuthResponse authResponse = 2;</code>
     */
    public Builder clearAuthResponse() {
      if (authResponseBuilder_ == null) {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
        }
        authResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.game.AuthResponse authResponse = 2;</code>
     */
    public com.fxy.game.message.AuthResponse.Builder getAuthResponseBuilder() {
      return internalGetAuthResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.game.AuthResponse authResponse = 2;</code>
     */
    @java.lang.Override
    public com.fxy.game.message.AuthResponseOrBuilder getAuthResponseOrBuilder() {
      if ((msgCase_ == 2) && (authResponseBuilder_ != null)) {
        return authResponseBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 2) {
          return (com.fxy.game.message.AuthResponse) msg_;
        }
        return com.fxy.game.message.AuthResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.game.AuthResponse authResponse = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.AuthResponse, com.fxy.game.message.AuthResponse.Builder, com.fxy.game.message.AuthResponseOrBuilder> 
        internalGetAuthResponseFieldBuilder() {
      if (authResponseBuilder_ == null) {
        if (!(msgCase_ == 2)) {
          msg_ = com.fxy.game.message.AuthResponse.getDefaultInstance();
        }
        authResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.fxy.game.message.AuthResponse, com.fxy.game.message.AuthResponse.Builder, com.fxy.game.message.AuthResponseOrBuilder>(
                (com.fxy.game.message.AuthResponse) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 2;
      onChanged();
      return authResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.ChatRequest, com.fxy.game.message.ChatRequest.Builder, com.fxy.game.message.ChatRequestOrBuilder> chatRequestBuilder_;
    /**
     * <code>.game.ChatRequest chatRequest = 3;</code>
     * @return Whether the chatRequest field is set.
     */
    @java.lang.Override
    public boolean hasChatRequest() {
      return msgCase_ == 3;
    }
    /**
     * <code>.game.ChatRequest chatRequest = 3;</code>
     * @return The chatRequest.
     */
    @java.lang.Override
    public com.fxy.game.message.ChatRequest getChatRequest() {
      if (chatRequestBuilder_ == null) {
        if (msgCase_ == 3) {
          return (com.fxy.game.message.ChatRequest) msg_;
        }
        return com.fxy.game.message.ChatRequest.getDefaultInstance();
      } else {
        if (msgCase_ == 3) {
          return chatRequestBuilder_.getMessage();
        }
        return com.fxy.game.message.ChatRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.game.ChatRequest chatRequest = 3;</code>
     */
    public Builder setChatRequest(com.fxy.game.message.ChatRequest value) {
      if (chatRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        chatRequestBuilder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.game.ChatRequest chatRequest = 3;</code>
     */
    public Builder setChatRequest(
        com.fxy.game.message.ChatRequest.Builder builderForValue) {
      if (chatRequestBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        chatRequestBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.game.ChatRequest chatRequest = 3;</code>
     */
    public Builder mergeChatRequest(com.fxy.game.message.ChatRequest value) {
      if (chatRequestBuilder_ == null) {
        if (msgCase_ == 3 &&
            msg_ != com.fxy.game.message.ChatRequest.getDefaultInstance()) {
          msg_ = com.fxy.game.message.ChatRequest.newBuilder((com.fxy.game.message.ChatRequest) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 3) {
          chatRequestBuilder_.mergeFrom(value);
        } else {
          chatRequestBuilder_.setMessage(value);
        }
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.game.ChatRequest chatRequest = 3;</code>
     */
    public Builder clearChatRequest() {
      if (chatRequestBuilder_ == null) {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
        }
        chatRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.game.ChatRequest chatRequest = 3;</code>
     */
    public com.fxy.game.message.ChatRequest.Builder getChatRequestBuilder() {
      return internalGetChatRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.game.ChatRequest chatRequest = 3;</code>
     */
    @java.lang.Override
    public com.fxy.game.message.ChatRequestOrBuilder getChatRequestOrBuilder() {
      if ((msgCase_ == 3) && (chatRequestBuilder_ != null)) {
        return chatRequestBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 3) {
          return (com.fxy.game.message.ChatRequest) msg_;
        }
        return com.fxy.game.message.ChatRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.game.ChatRequest chatRequest = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.ChatRequest, com.fxy.game.message.ChatRequest.Builder, com.fxy.game.message.ChatRequestOrBuilder> 
        internalGetChatRequestFieldBuilder() {
      if (chatRequestBuilder_ == null) {
        if (!(msgCase_ == 3)) {
          msg_ = com.fxy.game.message.ChatRequest.getDefaultInstance();
        }
        chatRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.fxy.game.message.ChatRequest, com.fxy.game.message.ChatRequest.Builder, com.fxy.game.message.ChatRequestOrBuilder>(
                (com.fxy.game.message.ChatRequest) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 3;
      onChanged();
      return chatRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.ChatResponse, com.fxy.game.message.ChatResponse.Builder, com.fxy.game.message.ChatResponseOrBuilder> chatResponseBuilder_;
    /**
     * <code>.game.ChatResponse chatResponse = 4;</code>
     * @return Whether the chatResponse field is set.
     */
    @java.lang.Override
    public boolean hasChatResponse() {
      return msgCase_ == 4;
    }
    /**
     * <code>.game.ChatResponse chatResponse = 4;</code>
     * @return The chatResponse.
     */
    @java.lang.Override
    public com.fxy.game.message.ChatResponse getChatResponse() {
      if (chatResponseBuilder_ == null) {
        if (msgCase_ == 4) {
          return (com.fxy.game.message.ChatResponse) msg_;
        }
        return com.fxy.game.message.ChatResponse.getDefaultInstance();
      } else {
        if (msgCase_ == 4) {
          return chatResponseBuilder_.getMessage();
        }
        return com.fxy.game.message.ChatResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.game.ChatResponse chatResponse = 4;</code>
     */
    public Builder setChatResponse(com.fxy.game.message.ChatResponse value) {
      if (chatResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        chatResponseBuilder_.setMessage(value);
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.game.ChatResponse chatResponse = 4;</code>
     */
    public Builder setChatResponse(
        com.fxy.game.message.ChatResponse.Builder builderForValue) {
      if (chatResponseBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        chatResponseBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.game.ChatResponse chatResponse = 4;</code>
     */
    public Builder mergeChatResponse(com.fxy.game.message.ChatResponse value) {
      if (chatResponseBuilder_ == null) {
        if (msgCase_ == 4 &&
            msg_ != com.fxy.game.message.ChatResponse.getDefaultInstance()) {
          msg_ = com.fxy.game.message.ChatResponse.newBuilder((com.fxy.game.message.ChatResponse) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 4) {
          chatResponseBuilder_.mergeFrom(value);
        } else {
          chatResponseBuilder_.setMessage(value);
        }
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.game.ChatResponse chatResponse = 4;</code>
     */
    public Builder clearChatResponse() {
      if (chatResponseBuilder_ == null) {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
        }
        chatResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.game.ChatResponse chatResponse = 4;</code>
     */
    public com.fxy.game.message.ChatResponse.Builder getChatResponseBuilder() {
      return internalGetChatResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.game.ChatResponse chatResponse = 4;</code>
     */
    @java.lang.Override
    public com.fxy.game.message.ChatResponseOrBuilder getChatResponseOrBuilder() {
      if ((msgCase_ == 4) && (chatResponseBuilder_ != null)) {
        return chatResponseBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 4) {
          return (com.fxy.game.message.ChatResponse) msg_;
        }
        return com.fxy.game.message.ChatResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.game.ChatResponse chatResponse = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.ChatResponse, com.fxy.game.message.ChatResponse.Builder, com.fxy.game.message.ChatResponseOrBuilder> 
        internalGetChatResponseFieldBuilder() {
      if (chatResponseBuilder_ == null) {
        if (!(msgCase_ == 4)) {
          msg_ = com.fxy.game.message.ChatResponse.getDefaultInstance();
        }
        chatResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.fxy.game.message.ChatResponse, com.fxy.game.message.ChatResponse.Builder, com.fxy.game.message.ChatResponseOrBuilder>(
                (com.fxy.game.message.ChatResponse) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 4;
      onChanged();
      return chatResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.GameAction, com.fxy.game.message.GameAction.Builder, com.fxy.game.message.GameActionOrBuilder> gameActionBuilder_;
    /**
     * <code>.game.GameAction gameAction = 5;</code>
     * @return Whether the gameAction field is set.
     */
    @java.lang.Override
    public boolean hasGameAction() {
      return msgCase_ == 5;
    }
    /**
     * <code>.game.GameAction gameAction = 5;</code>
     * @return The gameAction.
     */
    @java.lang.Override
    public com.fxy.game.message.GameAction getGameAction() {
      if (gameActionBuilder_ == null) {
        if (msgCase_ == 5) {
          return (com.fxy.game.message.GameAction) msg_;
        }
        return com.fxy.game.message.GameAction.getDefaultInstance();
      } else {
        if (msgCase_ == 5) {
          return gameActionBuilder_.getMessage();
        }
        return com.fxy.game.message.GameAction.getDefaultInstance();
      }
    }
    /**
     * <code>.game.GameAction gameAction = 5;</code>
     */
    public Builder setGameAction(com.fxy.game.message.GameAction value) {
      if (gameActionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        gameActionBuilder_.setMessage(value);
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.game.GameAction gameAction = 5;</code>
     */
    public Builder setGameAction(
        com.fxy.game.message.GameAction.Builder builderForValue) {
      if (gameActionBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        gameActionBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.game.GameAction gameAction = 5;</code>
     */
    public Builder mergeGameAction(com.fxy.game.message.GameAction value) {
      if (gameActionBuilder_ == null) {
        if (msgCase_ == 5 &&
            msg_ != com.fxy.game.message.GameAction.getDefaultInstance()) {
          msg_ = com.fxy.game.message.GameAction.newBuilder((com.fxy.game.message.GameAction) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 5) {
          gameActionBuilder_.mergeFrom(value);
        } else {
          gameActionBuilder_.setMessage(value);
        }
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.game.GameAction gameAction = 5;</code>
     */
    public Builder clearGameAction() {
      if (gameActionBuilder_ == null) {
        if (msgCase_ == 5) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 5) {
          msgCase_ = 0;
          msg_ = null;
        }
        gameActionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.game.GameAction gameAction = 5;</code>
     */
    public com.fxy.game.message.GameAction.Builder getGameActionBuilder() {
      return internalGetGameActionFieldBuilder().getBuilder();
    }
    /**
     * <code>.game.GameAction gameAction = 5;</code>
     */
    @java.lang.Override
    public com.fxy.game.message.GameActionOrBuilder getGameActionOrBuilder() {
      if ((msgCase_ == 5) && (gameActionBuilder_ != null)) {
        return gameActionBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 5) {
          return (com.fxy.game.message.GameAction) msg_;
        }
        return com.fxy.game.message.GameAction.getDefaultInstance();
      }
    }
    /**
     * <code>.game.GameAction gameAction = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.GameAction, com.fxy.game.message.GameAction.Builder, com.fxy.game.message.GameActionOrBuilder> 
        internalGetGameActionFieldBuilder() {
      if (gameActionBuilder_ == null) {
        if (!(msgCase_ == 5)) {
          msg_ = com.fxy.game.message.GameAction.getDefaultInstance();
        }
        gameActionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.fxy.game.message.GameAction, com.fxy.game.message.GameAction.Builder, com.fxy.game.message.GameActionOrBuilder>(
                (com.fxy.game.message.GameAction) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 5;
      onChanged();
      return gameActionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.GameState, com.fxy.game.message.GameState.Builder, com.fxy.game.message.GameStateOrBuilder> gameStateBuilder_;
    /**
     * <code>.game.GameState gameState = 6;</code>
     * @return Whether the gameState field is set.
     */
    @java.lang.Override
    public boolean hasGameState() {
      return msgCase_ == 6;
    }
    /**
     * <code>.game.GameState gameState = 6;</code>
     * @return The gameState.
     */
    @java.lang.Override
    public com.fxy.game.message.GameState getGameState() {
      if (gameStateBuilder_ == null) {
        if (msgCase_ == 6) {
          return (com.fxy.game.message.GameState) msg_;
        }
        return com.fxy.game.message.GameState.getDefaultInstance();
      } else {
        if (msgCase_ == 6) {
          return gameStateBuilder_.getMessage();
        }
        return com.fxy.game.message.GameState.getDefaultInstance();
      }
    }
    /**
     * <code>.game.GameState gameState = 6;</code>
     */
    public Builder setGameState(com.fxy.game.message.GameState value) {
      if (gameStateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        gameStateBuilder_.setMessage(value);
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.game.GameState gameState = 6;</code>
     */
    public Builder setGameState(
        com.fxy.game.message.GameState.Builder builderForValue) {
      if (gameStateBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        gameStateBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.game.GameState gameState = 6;</code>
     */
    public Builder mergeGameState(com.fxy.game.message.GameState value) {
      if (gameStateBuilder_ == null) {
        if (msgCase_ == 6 &&
            msg_ != com.fxy.game.message.GameState.getDefaultInstance()) {
          msg_ = com.fxy.game.message.GameState.newBuilder((com.fxy.game.message.GameState) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 6) {
          gameStateBuilder_.mergeFrom(value);
        } else {
          gameStateBuilder_.setMessage(value);
        }
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.game.GameState gameState = 6;</code>
     */
    public Builder clearGameState() {
      if (gameStateBuilder_ == null) {
        if (msgCase_ == 6) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 6) {
          msgCase_ = 0;
          msg_ = null;
        }
        gameStateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.game.GameState gameState = 6;</code>
     */
    public com.fxy.game.message.GameState.Builder getGameStateBuilder() {
      return internalGetGameStateFieldBuilder().getBuilder();
    }
    /**
     * <code>.game.GameState gameState = 6;</code>
     */
    @java.lang.Override
    public com.fxy.game.message.GameStateOrBuilder getGameStateOrBuilder() {
      if ((msgCase_ == 6) && (gameStateBuilder_ != null)) {
        return gameStateBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 6) {
          return (com.fxy.game.message.GameState) msg_;
        }
        return com.fxy.game.message.GameState.getDefaultInstance();
      }
    }
    /**
     * <code>.game.GameState gameState = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.GameState, com.fxy.game.message.GameState.Builder, com.fxy.game.message.GameStateOrBuilder> 
        internalGetGameStateFieldBuilder() {
      if (gameStateBuilder_ == null) {
        if (!(msgCase_ == 6)) {
          msg_ = com.fxy.game.message.GameState.getDefaultInstance();
        }
        gameStateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.fxy.game.message.GameState, com.fxy.game.message.GameState.Builder, com.fxy.game.message.GameStateOrBuilder>(
                (com.fxy.game.message.GameState) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 6;
      onChanged();
      return gameStateBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.ShopRequest, com.fxy.game.message.ShopRequest.Builder, com.fxy.game.message.ShopRequestOrBuilder> shopRequestBuilder_;
    /**
     * <code>.game.ShopRequest shopRequest = 7;</code>
     * @return Whether the shopRequest field is set.
     */
    @java.lang.Override
    public boolean hasShopRequest() {
      return msgCase_ == 7;
    }
    /**
     * <code>.game.ShopRequest shopRequest = 7;</code>
     * @return The shopRequest.
     */
    @java.lang.Override
    public com.fxy.game.message.ShopRequest getShopRequest() {
      if (shopRequestBuilder_ == null) {
        if (msgCase_ == 7) {
          return (com.fxy.game.message.ShopRequest) msg_;
        }
        return com.fxy.game.message.ShopRequest.getDefaultInstance();
      } else {
        if (msgCase_ == 7) {
          return shopRequestBuilder_.getMessage();
        }
        return com.fxy.game.message.ShopRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.game.ShopRequest shopRequest = 7;</code>
     */
    public Builder setShopRequest(com.fxy.game.message.ShopRequest value) {
      if (shopRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        shopRequestBuilder_.setMessage(value);
      }
      msgCase_ = 7;
      return this;
    }
    /**
     * <code>.game.ShopRequest shopRequest = 7;</code>
     */
    public Builder setShopRequest(
        com.fxy.game.message.ShopRequest.Builder builderForValue) {
      if (shopRequestBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        shopRequestBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 7;
      return this;
    }
    /**
     * <code>.game.ShopRequest shopRequest = 7;</code>
     */
    public Builder mergeShopRequest(com.fxy.game.message.ShopRequest value) {
      if (shopRequestBuilder_ == null) {
        if (msgCase_ == 7 &&
            msg_ != com.fxy.game.message.ShopRequest.getDefaultInstance()) {
          msg_ = com.fxy.game.message.ShopRequest.newBuilder((com.fxy.game.message.ShopRequest) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 7) {
          shopRequestBuilder_.mergeFrom(value);
        } else {
          shopRequestBuilder_.setMessage(value);
        }
      }
      msgCase_ = 7;
      return this;
    }
    /**
     * <code>.game.ShopRequest shopRequest = 7;</code>
     */
    public Builder clearShopRequest() {
      if (shopRequestBuilder_ == null) {
        if (msgCase_ == 7) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 7) {
          msgCase_ = 0;
          msg_ = null;
        }
        shopRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.game.ShopRequest shopRequest = 7;</code>
     */
    public com.fxy.game.message.ShopRequest.Builder getShopRequestBuilder() {
      return internalGetShopRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.game.ShopRequest shopRequest = 7;</code>
     */
    @java.lang.Override
    public com.fxy.game.message.ShopRequestOrBuilder getShopRequestOrBuilder() {
      if ((msgCase_ == 7) && (shopRequestBuilder_ != null)) {
        return shopRequestBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 7) {
          return (com.fxy.game.message.ShopRequest) msg_;
        }
        return com.fxy.game.message.ShopRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.game.ShopRequest shopRequest = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.ShopRequest, com.fxy.game.message.ShopRequest.Builder, com.fxy.game.message.ShopRequestOrBuilder> 
        internalGetShopRequestFieldBuilder() {
      if (shopRequestBuilder_ == null) {
        if (!(msgCase_ == 7)) {
          msg_ = com.fxy.game.message.ShopRequest.getDefaultInstance();
        }
        shopRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.fxy.game.message.ShopRequest, com.fxy.game.message.ShopRequest.Builder, com.fxy.game.message.ShopRequestOrBuilder>(
                (com.fxy.game.message.ShopRequest) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 7;
      onChanged();
      return shopRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.ShopResponse, com.fxy.game.message.ShopResponse.Builder, com.fxy.game.message.ShopResponseOrBuilder> shopResponseBuilder_;
    /**
     * <code>.game.ShopResponse shopResponse = 8;</code>
     * @return Whether the shopResponse field is set.
     */
    @java.lang.Override
    public boolean hasShopResponse() {
      return msgCase_ == 8;
    }
    /**
     * <code>.game.ShopResponse shopResponse = 8;</code>
     * @return The shopResponse.
     */
    @java.lang.Override
    public com.fxy.game.message.ShopResponse getShopResponse() {
      if (shopResponseBuilder_ == null) {
        if (msgCase_ == 8) {
          return (com.fxy.game.message.ShopResponse) msg_;
        }
        return com.fxy.game.message.ShopResponse.getDefaultInstance();
      } else {
        if (msgCase_ == 8) {
          return shopResponseBuilder_.getMessage();
        }
        return com.fxy.game.message.ShopResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.game.ShopResponse shopResponse = 8;</code>
     */
    public Builder setShopResponse(com.fxy.game.message.ShopResponse value) {
      if (shopResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        shopResponseBuilder_.setMessage(value);
      }
      msgCase_ = 8;
      return this;
    }
    /**
     * <code>.game.ShopResponse shopResponse = 8;</code>
     */
    public Builder setShopResponse(
        com.fxy.game.message.ShopResponse.Builder builderForValue) {
      if (shopResponseBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        shopResponseBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 8;
      return this;
    }
    /**
     * <code>.game.ShopResponse shopResponse = 8;</code>
     */
    public Builder mergeShopResponse(com.fxy.game.message.ShopResponse value) {
      if (shopResponseBuilder_ == null) {
        if (msgCase_ == 8 &&
            msg_ != com.fxy.game.message.ShopResponse.getDefaultInstance()) {
          msg_ = com.fxy.game.message.ShopResponse.newBuilder((com.fxy.game.message.ShopResponse) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 8) {
          shopResponseBuilder_.mergeFrom(value);
        } else {
          shopResponseBuilder_.setMessage(value);
        }
      }
      msgCase_ = 8;
      return this;
    }
    /**
     * <code>.game.ShopResponse shopResponse = 8;</code>
     */
    public Builder clearShopResponse() {
      if (shopResponseBuilder_ == null) {
        if (msgCase_ == 8) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 8) {
          msgCase_ = 0;
          msg_ = null;
        }
        shopResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.game.ShopResponse shopResponse = 8;</code>
     */
    public com.fxy.game.message.ShopResponse.Builder getShopResponseBuilder() {
      return internalGetShopResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.game.ShopResponse shopResponse = 8;</code>
     */
    @java.lang.Override
    public com.fxy.game.message.ShopResponseOrBuilder getShopResponseOrBuilder() {
      if ((msgCase_ == 8) && (shopResponseBuilder_ != null)) {
        return shopResponseBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 8) {
          return (com.fxy.game.message.ShopResponse) msg_;
        }
        return com.fxy.game.message.ShopResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.game.ShopResponse shopResponse = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.ShopResponse, com.fxy.game.message.ShopResponse.Builder, com.fxy.game.message.ShopResponseOrBuilder> 
        internalGetShopResponseFieldBuilder() {
      if (shopResponseBuilder_ == null) {
        if (!(msgCase_ == 8)) {
          msg_ = com.fxy.game.message.ShopResponse.getDefaultInstance();
        }
        shopResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.fxy.game.message.ShopResponse, com.fxy.game.message.ShopResponse.Builder, com.fxy.game.message.ShopResponseOrBuilder>(
                (com.fxy.game.message.ShopResponse) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 8;
      onChanged();
      return shopResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.MailRequest, com.fxy.game.message.MailRequest.Builder, com.fxy.game.message.MailRequestOrBuilder> mailRequestBuilder_;
    /**
     * <code>.game.MailRequest mailRequest = 9;</code>
     * @return Whether the mailRequest field is set.
     */
    @java.lang.Override
    public boolean hasMailRequest() {
      return msgCase_ == 9;
    }
    /**
     * <code>.game.MailRequest mailRequest = 9;</code>
     * @return The mailRequest.
     */
    @java.lang.Override
    public com.fxy.game.message.MailRequest getMailRequest() {
      if (mailRequestBuilder_ == null) {
        if (msgCase_ == 9) {
          return (com.fxy.game.message.MailRequest) msg_;
        }
        return com.fxy.game.message.MailRequest.getDefaultInstance();
      } else {
        if (msgCase_ == 9) {
          return mailRequestBuilder_.getMessage();
        }
        return com.fxy.game.message.MailRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.game.MailRequest mailRequest = 9;</code>
     */
    public Builder setMailRequest(com.fxy.game.message.MailRequest value) {
      if (mailRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        mailRequestBuilder_.setMessage(value);
      }
      msgCase_ = 9;
      return this;
    }
    /**
     * <code>.game.MailRequest mailRequest = 9;</code>
     */
    public Builder setMailRequest(
        com.fxy.game.message.MailRequest.Builder builderForValue) {
      if (mailRequestBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        mailRequestBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 9;
      return this;
    }
    /**
     * <code>.game.MailRequest mailRequest = 9;</code>
     */
    public Builder mergeMailRequest(com.fxy.game.message.MailRequest value) {
      if (mailRequestBuilder_ == null) {
        if (msgCase_ == 9 &&
            msg_ != com.fxy.game.message.MailRequest.getDefaultInstance()) {
          msg_ = com.fxy.game.message.MailRequest.newBuilder((com.fxy.game.message.MailRequest) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 9) {
          mailRequestBuilder_.mergeFrom(value);
        } else {
          mailRequestBuilder_.setMessage(value);
        }
      }
      msgCase_ = 9;
      return this;
    }
    /**
     * <code>.game.MailRequest mailRequest = 9;</code>
     */
    public Builder clearMailRequest() {
      if (mailRequestBuilder_ == null) {
        if (msgCase_ == 9) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 9) {
          msgCase_ = 0;
          msg_ = null;
        }
        mailRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.game.MailRequest mailRequest = 9;</code>
     */
    public com.fxy.game.message.MailRequest.Builder getMailRequestBuilder() {
      return internalGetMailRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.game.MailRequest mailRequest = 9;</code>
     */
    @java.lang.Override
    public com.fxy.game.message.MailRequestOrBuilder getMailRequestOrBuilder() {
      if ((msgCase_ == 9) && (mailRequestBuilder_ != null)) {
        return mailRequestBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 9) {
          return (com.fxy.game.message.MailRequest) msg_;
        }
        return com.fxy.game.message.MailRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.game.MailRequest mailRequest = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.MailRequest, com.fxy.game.message.MailRequest.Builder, com.fxy.game.message.MailRequestOrBuilder> 
        internalGetMailRequestFieldBuilder() {
      if (mailRequestBuilder_ == null) {
        if (!(msgCase_ == 9)) {
          msg_ = com.fxy.game.message.MailRequest.getDefaultInstance();
        }
        mailRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.fxy.game.message.MailRequest, com.fxy.game.message.MailRequest.Builder, com.fxy.game.message.MailRequestOrBuilder>(
                (com.fxy.game.message.MailRequest) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 9;
      onChanged();
      return mailRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.MailResponse, com.fxy.game.message.MailResponse.Builder, com.fxy.game.message.MailResponseOrBuilder> mailResponseBuilder_;
    /**
     * <code>.game.MailResponse mailResponse = 10;</code>
     * @return Whether the mailResponse field is set.
     */
    @java.lang.Override
    public boolean hasMailResponse() {
      return msgCase_ == 10;
    }
    /**
     * <code>.game.MailResponse mailResponse = 10;</code>
     * @return The mailResponse.
     */
    @java.lang.Override
    public com.fxy.game.message.MailResponse getMailResponse() {
      if (mailResponseBuilder_ == null) {
        if (msgCase_ == 10) {
          return (com.fxy.game.message.MailResponse) msg_;
        }
        return com.fxy.game.message.MailResponse.getDefaultInstance();
      } else {
        if (msgCase_ == 10) {
          return mailResponseBuilder_.getMessage();
        }
        return com.fxy.game.message.MailResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.game.MailResponse mailResponse = 10;</code>
     */
    public Builder setMailResponse(com.fxy.game.message.MailResponse value) {
      if (mailResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        mailResponseBuilder_.setMessage(value);
      }
      msgCase_ = 10;
      return this;
    }
    /**
     * <code>.game.MailResponse mailResponse = 10;</code>
     */
    public Builder setMailResponse(
        com.fxy.game.message.MailResponse.Builder builderForValue) {
      if (mailResponseBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        mailResponseBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 10;
      return this;
    }
    /**
     * <code>.game.MailResponse mailResponse = 10;</code>
     */
    public Builder mergeMailResponse(com.fxy.game.message.MailResponse value) {
      if (mailResponseBuilder_ == null) {
        if (msgCase_ == 10 &&
            msg_ != com.fxy.game.message.MailResponse.getDefaultInstance()) {
          msg_ = com.fxy.game.message.MailResponse.newBuilder((com.fxy.game.message.MailResponse) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 10) {
          mailResponseBuilder_.mergeFrom(value);
        } else {
          mailResponseBuilder_.setMessage(value);
        }
      }
      msgCase_ = 10;
      return this;
    }
    /**
     * <code>.game.MailResponse mailResponse = 10;</code>
     */
    public Builder clearMailResponse() {
      if (mailResponseBuilder_ == null) {
        if (msgCase_ == 10) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 10) {
          msgCase_ = 0;
          msg_ = null;
        }
        mailResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.game.MailResponse mailResponse = 10;</code>
     */
    public com.fxy.game.message.MailResponse.Builder getMailResponseBuilder() {
      return internalGetMailResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.game.MailResponse mailResponse = 10;</code>
     */
    @java.lang.Override
    public com.fxy.game.message.MailResponseOrBuilder getMailResponseOrBuilder() {
      if ((msgCase_ == 10) && (mailResponseBuilder_ != null)) {
        return mailResponseBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 10) {
          return (com.fxy.game.message.MailResponse) msg_;
        }
        return com.fxy.game.message.MailResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.game.MailResponse mailResponse = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.MailResponse, com.fxy.game.message.MailResponse.Builder, com.fxy.game.message.MailResponseOrBuilder> 
        internalGetMailResponseFieldBuilder() {
      if (mailResponseBuilder_ == null) {
        if (!(msgCase_ == 10)) {
          msg_ = com.fxy.game.message.MailResponse.getDefaultInstance();
        }
        mailResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.fxy.game.message.MailResponse, com.fxy.game.message.MailResponse.Builder, com.fxy.game.message.MailResponseOrBuilder>(
                (com.fxy.game.message.MailResponse) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 10;
      onChanged();
      return mailResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.RoleRequest, com.fxy.game.message.RoleRequest.Builder, com.fxy.game.message.RoleRequestOrBuilder> roleRequestBuilder_;
    /**
     * <code>.game.RoleRequest roleRequest = 11;</code>
     * @return Whether the roleRequest field is set.
     */
    @java.lang.Override
    public boolean hasRoleRequest() {
      return msgCase_ == 11;
    }
    /**
     * <code>.game.RoleRequest roleRequest = 11;</code>
     * @return The roleRequest.
     */
    @java.lang.Override
    public com.fxy.game.message.RoleRequest getRoleRequest() {
      if (roleRequestBuilder_ == null) {
        if (msgCase_ == 11) {
          return (com.fxy.game.message.RoleRequest) msg_;
        }
        return com.fxy.game.message.RoleRequest.getDefaultInstance();
      } else {
        if (msgCase_ == 11) {
          return roleRequestBuilder_.getMessage();
        }
        return com.fxy.game.message.RoleRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.game.RoleRequest roleRequest = 11;</code>
     */
    public Builder setRoleRequest(com.fxy.game.message.RoleRequest value) {
      if (roleRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        roleRequestBuilder_.setMessage(value);
      }
      msgCase_ = 11;
      return this;
    }
    /**
     * <code>.game.RoleRequest roleRequest = 11;</code>
     */
    public Builder setRoleRequest(
        com.fxy.game.message.RoleRequest.Builder builderForValue) {
      if (roleRequestBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        roleRequestBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 11;
      return this;
    }
    /**
     * <code>.game.RoleRequest roleRequest = 11;</code>
     */
    public Builder mergeRoleRequest(com.fxy.game.message.RoleRequest value) {
      if (roleRequestBuilder_ == null) {
        if (msgCase_ == 11 &&
            msg_ != com.fxy.game.message.RoleRequest.getDefaultInstance()) {
          msg_ = com.fxy.game.message.RoleRequest.newBuilder((com.fxy.game.message.RoleRequest) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 11) {
          roleRequestBuilder_.mergeFrom(value);
        } else {
          roleRequestBuilder_.setMessage(value);
        }
      }
      msgCase_ = 11;
      return this;
    }
    /**
     * <code>.game.RoleRequest roleRequest = 11;</code>
     */
    public Builder clearRoleRequest() {
      if (roleRequestBuilder_ == null) {
        if (msgCase_ == 11) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 11) {
          msgCase_ = 0;
          msg_ = null;
        }
        roleRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.game.RoleRequest roleRequest = 11;</code>
     */
    public com.fxy.game.message.RoleRequest.Builder getRoleRequestBuilder() {
      return internalGetRoleRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.game.RoleRequest roleRequest = 11;</code>
     */
    @java.lang.Override
    public com.fxy.game.message.RoleRequestOrBuilder getRoleRequestOrBuilder() {
      if ((msgCase_ == 11) && (roleRequestBuilder_ != null)) {
        return roleRequestBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 11) {
          return (com.fxy.game.message.RoleRequest) msg_;
        }
        return com.fxy.game.message.RoleRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.game.RoleRequest roleRequest = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.RoleRequest, com.fxy.game.message.RoleRequest.Builder, com.fxy.game.message.RoleRequestOrBuilder> 
        internalGetRoleRequestFieldBuilder() {
      if (roleRequestBuilder_ == null) {
        if (!(msgCase_ == 11)) {
          msg_ = com.fxy.game.message.RoleRequest.getDefaultInstance();
        }
        roleRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.fxy.game.message.RoleRequest, com.fxy.game.message.RoleRequest.Builder, com.fxy.game.message.RoleRequestOrBuilder>(
                (com.fxy.game.message.RoleRequest) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 11;
      onChanged();
      return roleRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.RoleResponse, com.fxy.game.message.RoleResponse.Builder, com.fxy.game.message.RoleResponseOrBuilder> roleResponseBuilder_;
    /**
     * <code>.game.RoleResponse roleResponse = 12;</code>
     * @return Whether the roleResponse field is set.
     */
    @java.lang.Override
    public boolean hasRoleResponse() {
      return msgCase_ == 12;
    }
    /**
     * <code>.game.RoleResponse roleResponse = 12;</code>
     * @return The roleResponse.
     */
    @java.lang.Override
    public com.fxy.game.message.RoleResponse getRoleResponse() {
      if (roleResponseBuilder_ == null) {
        if (msgCase_ == 12) {
          return (com.fxy.game.message.RoleResponse) msg_;
        }
        return com.fxy.game.message.RoleResponse.getDefaultInstance();
      } else {
        if (msgCase_ == 12) {
          return roleResponseBuilder_.getMessage();
        }
        return com.fxy.game.message.RoleResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.game.RoleResponse roleResponse = 12;</code>
     */
    public Builder setRoleResponse(com.fxy.game.message.RoleResponse value) {
      if (roleResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        roleResponseBuilder_.setMessage(value);
      }
      msgCase_ = 12;
      return this;
    }
    /**
     * <code>.game.RoleResponse roleResponse = 12;</code>
     */
    public Builder setRoleResponse(
        com.fxy.game.message.RoleResponse.Builder builderForValue) {
      if (roleResponseBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        roleResponseBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 12;
      return this;
    }
    /**
     * <code>.game.RoleResponse roleResponse = 12;</code>
     */
    public Builder mergeRoleResponse(com.fxy.game.message.RoleResponse value) {
      if (roleResponseBuilder_ == null) {
        if (msgCase_ == 12 &&
            msg_ != com.fxy.game.message.RoleResponse.getDefaultInstance()) {
          msg_ = com.fxy.game.message.RoleResponse.newBuilder((com.fxy.game.message.RoleResponse) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 12) {
          roleResponseBuilder_.mergeFrom(value);
        } else {
          roleResponseBuilder_.setMessage(value);
        }
      }
      msgCase_ = 12;
      return this;
    }
    /**
     * <code>.game.RoleResponse roleResponse = 12;</code>
     */
    public Builder clearRoleResponse() {
      if (roleResponseBuilder_ == null) {
        if (msgCase_ == 12) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 12) {
          msgCase_ = 0;
          msg_ = null;
        }
        roleResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.game.RoleResponse roleResponse = 12;</code>
     */
    public com.fxy.game.message.RoleResponse.Builder getRoleResponseBuilder() {
      return internalGetRoleResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.game.RoleResponse roleResponse = 12;</code>
     */
    @java.lang.Override
    public com.fxy.game.message.RoleResponseOrBuilder getRoleResponseOrBuilder() {
      if ((msgCase_ == 12) && (roleResponseBuilder_ != null)) {
        return roleResponseBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 12) {
          return (com.fxy.game.message.RoleResponse) msg_;
        }
        return com.fxy.game.message.RoleResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.game.RoleResponse roleResponse = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.fxy.game.message.RoleResponse, com.fxy.game.message.RoleResponse.Builder, com.fxy.game.message.RoleResponseOrBuilder> 
        internalGetRoleResponseFieldBuilder() {
      if (roleResponseBuilder_ == null) {
        if (!(msgCase_ == 12)) {
          msg_ = com.fxy.game.message.RoleResponse.getDefaultInstance();
        }
        roleResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.fxy.game.message.RoleResponse, com.fxy.game.message.RoleResponse.Builder, com.fxy.game.message.RoleResponseOrBuilder>(
                (com.fxy.game.message.RoleResponse) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 12;
      onChanged();
      return roleResponseBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:game.Wrapper)
  }

  // @@protoc_insertion_point(class_scope:game.Wrapper)
  private static final com.fxy.game.message.Wrapper DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fxy.game.message.Wrapper();
  }

  public static com.fxy.game.message.Wrapper getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Wrapper>
      PARSER = new com.google.protobuf.AbstractParser<Wrapper>() {
    @java.lang.Override
    public Wrapper parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Wrapper> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Wrapper> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.fxy.game.message.Wrapper getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

